// START A3HEADER
//
// This source file is part of the Atlantis PBM game program.
// Copyright (C) 1995-1999 Geoff Dunbar
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation; either version 2
// of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program, in the file license.txt. If not, write
// to the Free Software Foundation, Inc., 59 Temple Place - Suite 330,
// Boston, MA 02111-1307, USA.
//
// See the Atlantis Project web page for details:
// http://www.prankster.com/project
//
// END A3HEADER
//
#ifndef RULES_H
#define RULES_H

//
// The items
//
enum {
	// races still needed
	I_LEADERS,				//0
	I_MAN,					//1
	I_SLAVE,				//369
	I_MERCENARY,				//370
	I_LIZARDMAN,
	I_LLIZARDMAN,
	I_DRAGONLORD,
	I_LDRAGONLORD,
	I_BONDSMAN,				//629
	I_LBONDSMAN,
	//races for battleground
	I_TLHIGHELF,				//22
	I_TRELF,				//23
	I_TLLOWLANDER,				//8
	I_TRBARBARIAN,				//9
	I_TLHIGHLANDER,				//10
	I_TRCLANSMAN,				//11
	I_TLDERVISH,				//6
	I_TRNOMAD,				//7
	I_TLDWARF,				//28
	I_TRDWARF,				//29
	I_TLHALFLING,				//20
	I_TRHALFLING,				//21
	I_TLGNOME,				//26
	I_TRGNOME,				//27
	I_TLHOBGOBLIN,				//30
	I_TRGOBLIN,				//31
	I_TLURUK,				//38
	I_TRORC,				//39
	I_TLOGRE,				//44
	I_TROGRE,				//45
	I_TLMINOTAUR,				//52
	I_TRMINOTAUR,				//53
	I_TLTROLL,				//36
	I_TRGNOLL,				//37
	I_TLSANDLING,				//34
	I_TRSANDLING,				//35
	//phantastic monsters
	I_IDRAGON,				//280
	I_IWOLF,				//281
	I_IEAGLE,				//282
	I_ISKELETON,				//283
	I_IUNDEAD,				//284
	I_ILICH,				//285
	I_IIMP,					//286
	I_IDEMON,				//287
	I_IBALROG,				//288
	I_ISTEELDRAGON,				
	I_ICOPPERDRAGON,				
	I_IBRONZEDRAGON,				
	I_ISILVERDRAGON,				
	I_IGOLDENDRAGON,				
	I_IGREENDRAGON,				
	I_IBROWNDRAGON,				
	I_IBLUEDRAGON,				
	I_IREDDRAGON,				
	I_IWHITEDRAGON,				
	I_IBLACKDRAGON,		
	//real monsters
	I_EAGLE,				//289
	I_STEELDRAGON,				//290
	I_COPPERDRAGON,				//291
	I_BRONZEDRAGON,				//292
	I_SILVERDRAGON,				//293
	I_GOLDENDRAGON,				//294
	I_WOLF,					//295
	//small animal monsters
	I_CROW,					//296
	I_MOUNTAINLION,				//297
	I_GIANTRAT,				//298
	I_SNAKE,				//299
	I_LION,					//300
	I_ICEWOLF,				//301
	I_POISONSPIDER,				//302
	I_FANGEDLIZARD,				//303
	I_CRAWLER,				//304
	//medium animal monsters
	I_LIVINGTREE,				//305
	I_GRIZZLYBEAR,				//306
	I_ROC,					//307
	I_SWAMPCREATURE,			//308
	I_TIGER,				//309
	I_GIANTSCORPION,			//310
	I_POLARBEAR,				//311
	I_GIANTSQUID,				//312
	I_BUGBEAR,				//313
	I_MAULER,				//314
	I_TUNNELWORM,				//315
	//special animal monsters
	I_GREENDRAGON,				//316
	I_BROWNDRAGON,				//317
	I_BLUEDRAGON,				//318
	I_REDDRAGON,				//319
	I_WHITEDRAGON,				//320
	I_BLACKDRAGON,				//321
	I_BOGTHING,				//322
	I_HYDRA,				//323
	I_SPHINX,				//324
	I_KRAKEN,				//325
	I_ILLYRTHID,				//326
	//small humanoid monsters
	I_THIEF,				//327
	I_HIGHWAYMAN,				//328
	I_GOBLIN,				//329
	I_SKELETON,				//330
	I_IMP,					//331
	I_PIRATE,				//332
	I_MERFOLK,				//333
	I_MUTANT,				//334
	I_CENTAUR,				//335
	I_KOBOLD,				//336
	I_WILDMAN,				//337
	I_SANDLING,				//338
	//medium humanoid monsters
	I_DROWWARRIOR,				//339
	I_EVILWARRIOR,				//340
	I_OGRE,					//341
	I_YETI,					//342
	I_TROLL,				//343
	I_ETTIN,				//344
	I_UNDEAD,				//345
	I_DEMON,				//346
	//special humanoid monsters
	I_BALROG,				//347
	I_LICH,					//348
	I_STORMGIANT,				//349
	I_CLOUDGIANT,				//350
	I_EVILSORCERER,				//351
	I_EVILMAGICIAN,				//352
	I_DARKPRIEST,				//353
	//very small monsters for trade structures
	I_ZOMBIE,				//511
	I_RAT,					//512
	I_ANIMATEDTREE,				//513
	I_WILLOWWISP,				//514
	I_CARNIVOROUSPLANT,			//515
	I_KILLERLION,				//516
	I_LONELYCROW,				//517
	I_POISONSNAKE,				//518
	I_WILDBOAR,				//519
	I_LONELYWOLF,				//520
	I_LONELYFANGEDLIZARD,			//521
	I_LONELYPOISONSPIDER,			//522
	I_LONELYCRAWLER,			//523
	I_LONELYEVILWARRIOR,			//524
	I_ROBBER,				//525
	//monster spoils
	I_DRAGONSCALES,				//354
	I_DRAGONBLOOD,				//355
	I_SWAMPCRYSTAL,				//356
	I_HYDRABLOOD,				//357
	I_TOME,					//358
	I_RUBY,					//359
	I_KRAKENEYE,				//360
	I_ILLYRTHIDBRAIN,			//361
	I_BEARCLAWS,				//362
	I_ROCFEATHER,				//363
	I_SLIME,				//364
	I_SQUIDBEAK,				//365
	I_ACID,					//366
	I_EGG,					//367
	I_RATTAIL,				//368
	//ressources
	I_SILVER,				//58
	I_GRAIN,				//59
	I_MUSHROOM,				//60
	I_GRAPES,				//61
	I_COTTON,				//62
	I_TRUFFLES,				//63
	I_TOBACCO,				//64
	I_DYEPLANT,				//65
	I_SHEEP,				//66
	I_WOOLINGER,				//67
	I_LIVESTOCK,				//68
	I_LIZARD,				//69
	I_POINTYEAREDSHEEP,			//70
	I_SPIDER,				//71
	I_FISH,					//72
	I_MUSSELS,				//73
	I_WHALE,				//74
	I_IRON,					//75
	I_ROUGHGEM,				//76
	I_MITHRIL,				//77
	I_ADMANTIUM,				//78
	I_GOLD,					//79
	I_WOOD,					//80
	I_IRONWOOD,				//81
	I_YEW,					//82
	I_STONE,				//83
	I_ROOTSTONE,				//84
	I_CORESTONE,				//85
	I_GAME,					//86
	I_FURREDANIMAL,				//87
	I_MARSHGAS,				//88
	I_PELTANIMAL,				//89
	I_HERB,					//90
	I_FUNGUS,				//91
	I_MEDICINEPLANT,			//92
	//Mounts
	I_PONY,					//93
	I_GIANTWOLF,				//94
	I_GIANTSPIDER,				//95
	I_HORSE,				//96
	I_CAMEL,				//97
	I_GIANTLIZARD,				//98
	I_GIANTEAGLE,				//99
	I_GIANTBAT,				//100
	I_ELEPHANT,				//101
	I_MAMMOTH,				//102
	I_GIANTMOLE,				//103
	I_WINGEDHORSE,				//104
	I_FLYINGLIZARD,				//105
	//Mounts for evil races
	I_WARG,					//106
	I_WARHORSE,				//107
	I_WARLIZARD,				//108
	I_HARPY,				//109
	I_GIANTCENTIPEDE,			//110
	I_CHIMERA,				//111
	I_WALKINGFORTRESS,			//627
	I_WARMAMMOTH,				//112
	I_FIRELIZARD,				//113
	//Mounts for good races
	I_HUNTINGDOG,				//114
	I_CHARGER,				//115
	I_BATTLELIZARD,				//116
	I_UNICORN,				//117
	I_DRAKE,				//118
	I_GRIFFON,				//119
	I_BEHEMOTH,				//628
	I_WARELEPHANT,				//120
	I_FIREDRAKE,				//121
	//trade goods
	I_MEAT,					//122
	I_HIDE,					//123
	I_RATION,				//124
	I_FOOD,					//125
	I_DELICATESSEN,				//126
	I_BEER,					//127
	I_WINE,					//128
	I_CLOTHES,				//129
	I_PARFAIT,				//130
	I_CIGARS,				//131
	I_DYE,					//132
	I_WOOL,					//133
	I_CASHMERE,				//134
	I_POISON,				//135
	I_GARMENT,				//136
	I_PEARL,				//137
	I_OIL,					//138
	I_CHAIN,				//139
	I_GEM,					//140
	I_JEWELRY,				//141
	I_RING,					//596
	I_MIRROR,				//142
	I_ORNAMENT,				//143
	I_NECKLACE,				//144
	I_FURNITURE,				//145
	I_STRONGBOX,				//146
	I_IDOL,					//147
	I_STATUE,				//148
	I_FIGURINE,				//149
	I_TALISMAN,				//150
	I_FUR,					//151
	I_PELT,					//152
	I_FURCOAT,				//153
	I_PELTCOAT,				//154
	I_PERFUME,				//155
	I_HEALINGDRAFT,				//156
	I_MEDICINE,				//157
	I_HEALINGPOTION,			//158
	//tools
	I_SPINNINGWHEEL,			//159
	I_BARREL,				//160
	I_WAGON,				//161
	I_OXCART,				//162
	I_CARRIAGE,				//163
	I_LIZARDWAGON,				//164
	I_LIZARDCART,				//165
	I_LIZARDCARRIAGE,			//166
	I_PRESS,				//167
	I_LOOM,					//168
	I_HARP,					//169
	I_GLIDER,				//170
	I_NET,					//171
	I_LASSO,				//172
	I_BAG,					//173
	I_CUTLERY,				//174
	I_SAW,					//175
	I_CHISEL,				//176
	//weapons
	I_JAVELIN,				//177
	I_ENCHANTEDJAVELIN,			//178
	I_LIGHTCROSSBOW,			//179
	I_ENHANTEDLIGHTCROSSBOW,		//180
	I_CROSSBOW,				//181
	I_HEAVYCROSSBOW,			//182
	I_SHORTBOW,				//183
	I_ENCHANTEDSHORTBOW,			//184
	I_BOW,					//185
	I_LONGBOW,				//186
	I_PICK,					//187
	I_ENCHANTEDPICK,			//188
	I_SPEAR,				//189
	I_ENCHANTEDSPEAR,			//190
	I_PIKE,					//191
	I_ENCHANTEDPIKE,			//192
	I_LANCE,				//193
	I_ENCHANTEDLANCE,			//194
	I_HALBERD,				//195
	I_ENRUNEDSPEAR,				//196
	I_FIRESPEAR,				//197
	I_ICESPEAR,				//198
	I_QUARTERSTAFF,				//199
	I_ENCHANTEDQUARTERSTAFF,		//200
	I_BATTLESTAFF,				//201
	I_MAGESTAFF,				//202
	I_CLUB,					//203
	I_ENCHANTEDCLUB,			//204
	I_MACE,					//205
	I_ENCHANTEDMACE,			//206
	I_BATTLEMACE,				//207
	I_WARMACE,				//208
	I_HAMMER,				//209
	I_ENCHANTEDHAMMER,			//210
	I_MORNINGSTAR,				//211
	I_ENCHANTEDMORNINGSTAR,			//212
	I_BATTLEHAMMER,				//213
	I_ENCHANTEDBATTLEHAMMER,		//214
	I_SKULLCRUSHER,				//215
	I_AXE,					//216
	I_ENCHANTEDAXE,				//217
	I_BATTLEAXE,				//218
	I_ENCHANTEDBATTLEAXE,			//219
	I_CLEAVER,				//220
	I_ENRUNEDAXE,				//221
	I_WARAXE,				//222
	I_SWIFTAXE,				//223
	I_KNIFE,				//224
	I_ENCHANTEDKNIFE,			//225
	I_DAGGER,				//226
	I_ENCHANTEDDAGGER,			//227
	I_PARRYINGDAGGER,			//228
	I_ENCHANTEDPARRYINGDAGGER,		//229
	I_MITHRILDAGGER,			//230
	I_ADMANTIUMDAGGER,			//231
	I_SABRE,				//232
	I_ENCHANTEDSABRE,			//233
	I_EPEE,					//234
	I_FOIL,					//235
	I_SWORD,				//236
	I_ENCHANTEDSWORD,			//237
	I_BROADSWORD,				//238
	I_ENCHANTEDBROADSWORD,			//239
	I_LONGSWORD,				//240
	I_ENCHANTEDLONGSWORD,			//241
	I_MITHRILSWORD,				//242
	I_MITHRILBROADSWORD,			//243
	I_MITHRILLONGSWORD,			//244
	I_ADMANTIUMSWORD,			//245
	I_ADMANTIUMBROADSWORD,			//246
	I_ADMANTIUMLONGSWORD,			//247
	I_FLAMINGSWORD,				//248
	I_RUNESWORD,				//249
	I_BATTLESPEAR,				//526
	I_WARSPEAR,				//527
	I_BARDICHE,				//528
	I_BATTLELANCE,				//529
	I_WARLANCE,				//530
	I_WARSTAFF,				//531
	I_TRISTAR,				//532
	I_EVENINGSTAR,				//533
	I_WARHAMMER,				//534
	//armour
	I_SHIELD,				//250
	I_CLOTHARMOR,				//251
	I_LEATHERARMOR,				//252
	I_BARBARIANPLATE,			//253
	I_IRONCHAINARMOR,			//254
	I_IRONSCALEARMOR,			//255
	I_IRONPLATEARMOR,			//256
	I_MITHRILCHAINARMOR,			//257
	I_MITHRILSCALEARMOR,			//258
	I_MITHRILPLATEARMOR,			//259
	I_ADMANTIUMCHAINARMOR,			//260
	I_ADMANTIUMSCALEARMOR,			//261
	I_ADMANTIUMPLATEARMOR,			//262
	I_DRAGONSCALESARMOR,			//263
	I_CLOAKOFINVULNERABILITY,		//264
	I_ENCHANTEDCLOTHARMOR,			//265
	I_ENCHANTEDLEATHERARMOR,		//266
	I_ENCHANTEDCHAINARMOR,			//267
	I_ENCHANTEDSCALEARMOR,			//268
	I_ENCHANTEDPLATEARMOR,			//269
	//skill boost items
	I_IRINGOFSEAMANSHIP,
	I_IRINGOFINCREDIBLECOMBATPROWESS,
	I_IRINGOFHORSEMANSHIP,
	I_IRINGOFAIMING,
	I_IRINGOFARCHERY,
	I_AMULETOFHAUTECUISINE,
	I_AMULETOFARCHITECTURE,
	I_AMULETOFDOCKYARDS,
	I_AMULETOFCARPENTRY,
	I_AMULETOFSMITHCRAFT,
	I_HEALINGCHARM,
	I_FUNNYCHARM,
	I_VEGETABLECHARM,
	I_BEASTCHARM,
	I_FISHCHARM,
	I_WILDERNESSCHARM,
	I_HERBALCHARM,
	I_ORECHARM,
	I_WOODENCHARM,
	I_ROCKCHARM,
	I_PETCHARM,
	//items out of monster spoils
	I_CLOAKOFBLOOD,				//614
	I_STAFFOFPOWER,				//615
	I_STAFFOFFLAME,				//616
	I_STAFFOFCOLDNESS,			//617
	I_BLOODSWORD,				//618
	I_GLASSESOFTRUESIGHT,			//619
	I_CROWNOFINVISIBILITY,			//620
	I_AMULETTOFBEARSTRENGTH,		//621
	I_FEATHERCHARM,				//622
	I_INVISIBILITYPASTE,			//623
	I_WATERMASK,				//624
	I_STAFFOFACIDSHOWER,			//625
	I_AMULETTOFROCSIGHT,			//626
	I_RINGOFWARDING,			//535
	//magic items
	I_BOOTS,				//270
	I_AMULETOFI,				//271
	I_RINGOFI,				//272
	I_STAFFOFF,				//273
	I_STAFFOFL,				//274
	I_AMULETOFTS,				//275
	I_AMULETOFP,				//276
	I_SHIELDSTONE,				//277
	I_MCARPET,				//278
	I_PORTAL,				//279
	I_STAFFOFICE,
	I_STAFFOFMIND,
	I_ICESWORD,
	I_SOULEATER,
	I_CORONETOFPROTECTION,
	NITEMS
};

//
// Types of men.
//
enum {
	MAN_NONE,				//0
	MAN_LEADER,				//1
	MAN_MAN,				//2
	MAN_SLAVE,				//59
	MAN_MERC,				//60
	MAN_TLHIGHELF,
	MAN_TRELF,
	MAN_TLLOWLANDER,
	MAN_TRBARBARIAN,
	MAN_TLHIGHLANDER,
	MAN_TRCLANSMAN,
	MAN_TLDERVISH,
	MAN_TRNOMAD,
	MAN_TLDWARF,
	MAN_TRDWARF,
	MAN_TLHALFLING,
	MAN_TRHALFLING,
	MAN_TLGNOME,
	MAN_TRGNOME,
	MAN_TLHOBGOBLIN,
	MAN_TRGOBLIN,
	MAN_TLURUK,
	MAN_TRORC,
	MAN_TLOGRE,
	MAN_TROGRE,
	MAN_TLMINOTAUR,
	MAN_TRMINOTAUR,
	MAN_TLTROLL,
	MAN_TRGNOLL,
	MAN_TLSANDLING,
	MAN_TRSANDLING,
	NUMMAN
};

//
// Types of monsters
//
enum {
  MONSTER_NONE,					//0
  //producable
  MONSTER_WARG,					//1
  MONSTER_WHOR,					//2
  MONSTER_WLIZ,					//3
  MONSTER_HARY,					//4
  MONSTER_GCEN,					//5
  MONSTER_CHIM,					//6
  MONSTER_BEHEMOTH,				//147
  MONSTER_WMAM,					//7
  MONSTER_FLIZ,					//8
  MONSTER_HUND,					//9
  MONSTER_CHAR,					//10
  MONSTER_BLIZ,					//11
  MONSTER_UNIC,					//12
  MONSTER_DRAK,					//13
  MONSTER_GRIF,					//14
  MONSTER_WALKINGFORTRESS,			//146
  MONSTER_WELE,					//15
  MONSTER_FDRA,					//16
  //illusion
  MONSTER_ILLUSION,				//17
  MONSTER_EAGLES,				//18
  MONSTER_STEELDRAGON,				//19
  MONSTER_COPPERDRAGON,				//20
  MONSTER_BRONZEDRAGON,				//21
  MONSTER_SILVERDRAGON,				//22
  MONSTER_GOLDENDRAGON,				//23
  MONSTER_ZOMBIE,				//24
  MONSTER_RAT,					//25
  MONSTER_THIEF,				//26
  MONSTER_ANIMATEDTREE,				//27
  MONSTER_WILLOWWISP,				//28
  MONSTER_CARNIVOROUSPLANT,			//29
  MONSTER_KILLERLION,				//30
  MONSTER_CROW,					//31
  MONSTER_SNAKE,				//32
  MONSTER_WILDBOAR,				//33
  MONSTER_WOLF,					//34
  MONSTER_FANGEDLIZARD,				//35
  MONSTER_POISONSPIDER,				//36
  MONSTER_CRAWLER,				//37
  MONSTER_EVILWARRIOR,				//38
  MONSTER_HIGHWAYMAN,				//39
  MONSTER_ROBBER,				//40
  MONSTER_WOLVES,				//41
  MONSTER_CROWS,				//42
  MONSTER_MOUNTAINLIONS,			//43
  MONSTER_GIANTRATS,				//44
  MONSTER_SNAKES,				//45
  MONSTER_LIONS,				//46
  MONSTER_ICEWOLVES,				//47
  MONSTER_POISONSPIDERS,			//48
  MONSTER_FANGEDLIZARDS,			//49
  MONSTER_CRAWLERS,				//50
  MONSTER_LIVINGTREES,				//51
  MONSTER_GRIZZLYBEARS,				//52
  MONSTER_ROCS,					//53
  MONSTER_SWAMPCREATURES,			//54
  MONSTER_TIGERS,				//55
  MONSTER_GIANTSCORPIONS,			//56
  MONSTER_POLARBEARS,				//57
  MONSTER_GIANTSQUID,				//58
  MONSTER_BUGBEARS,				//59
  MONSTER_MAULER,				//60
  MONSTER_TUNNELWORM,				//61
  MONSTER_GREENDRAGON,				//62
  MONSTER_BROWNDRAGON,				//63
  MONSTER_BLUEDRAGON,				//64
  MONSTER_REDDRAGON,				//65
  MONSTER_WHITEDRAGON,				//66
  MONSTER_BLACKDRAGON,				//67
  MONSTER_BOGTHING,				//68
  MONSTER_HYDRA,				//69
  MONSTER_SPHINX,				//70
  MONSTER_KRAKEN,				//71
  MONSTER_ILLYRTHIL,				//72
  MONSTER_GOBLINS,				//73
  MONSTER_SKELETONS,				//74
  MONSTER_IMPS,					//75
  MONSTER_PIRATES,				//76
  MONSTER_MERFOLK,				//77
  MONSTER_MUTANTS,				//78
  MONSTER_CENTAURS,				//79
  MONSTER_KOBOLDS,				//80
  MONSTER_WILDMEN,				//81
  MONSTER_SANDLINGS,				//82
  MONSTER_DROWWARRIORS,				//83
  MONSTER_EVILWARRIORS,				//84
  MONSTER_OGRES,				//85
  MONSTER_YETIS,				//86
  MONSTER_TROLLS,				//87
  MONSTER_ETTINS,				//88
  MONSTER_UNDEAD,				//89
  MONSTER_DEMONS,				//90
  MONSTER_BALROG,				//91
  MONSTER_LICH,					//92
  MONSTER_STORMGIANT,				//93
  MONSTER_CLOUDGIANT,				//94
  MONSTER_EVILSORCERERS,			//95
  MONSTER_EVILMAGICIANS,			//96
  MONSTER_DARKPRIEST,				//97
  NUMMONSTERS
};

//
// Types of weapons
//
enum {
	WEAPON_NONE,				//
	WEAPON_RUNESWORD,			//
	WEAPON_BLOODSWORD,			//
	WEAPON_SOULEATER,
	WEAPON_ICESWORD,
	WEAPON_FLAMINGSWORD,			//
	WEAPON_LONGBOW,				//
	WEAPON_HEAVYCROSSBOW,			//
	WEAPON_CROSSBOW,			//
	WEAPON_BOW,				//
	WEAPON_ENCHANTEDSHORTBOW,		//
	WEAPON_ENCHANTEDLIGHTCROSSBOW,		//
	WEAPON_SHORTBOW,			//
	WEAPON_LIGHTCROSSBOW,			//
	WEAPON_ENCHANTEDJAVELIN,		//
	WEAPON_JAVELIN,				//
	WEAPON_MAGESTAFF,			//
	WEAPON_SWIFTAXE,			//
	WEAPON_ICESPEAR,			//
	WEAPON_FIRESPEAR,			//
	WEAPON_DWARVINBATTLEAXE,		//
	WEAPON_ADLONGSWORD,			//
	WEAPON_FOIL,				//
	WEAPON_WARHAMMER,			//
	WEAPON_WARMACE,				//
	WEAPON_ADBROADSWORD,			//
	WEAPON_BARDICHE,			//
	WEAPON_WARAXE,				//
	WEAPON_ADSWORD,				//
	WEAPON_WARLANCE,			//
	WEAPON_WARSPEAR,			//
	WEAPON_WARSTAFF,			//
	WEAPON_EVENINGSTAR,			//
	WEAPON_MILONGSWORD,			//
	WEAPON_EPEE,				//
	WEAPON_SKULLCRUSHER,			//
	WEAPON_MIBROADSWORD,			//
	WEAPON_BATTLEMACE,			//
	WEAPON_ENCHANTEDLONGSWORD,		//
	WEAPON_CLEAVER,				//
	WEAPON_HALBERD,				//
	WEAPON_ADDAGGER,			//
	WEAPON_ENCHANTEDSABRE,			//
	WEAPON_MISWORD,				//
	WEAPON_ENCHANTEDBATTLEHAMMER,		//
	WEAPON_ENCHANTEDBROADSWORD,		//
	WEAPON_ENCHANTEDMACE,			//
	WEAPON_BATTLELANCE,			//
	WEAPON_BATTLESPEAR,			//
	WEAPON_TRISTAR,				//
	WEAPON_ENCHANTEDBATTLEAXE,		//
	WEAPON_ENCHANTEDPIKE,			//
	WEAPON_BATTLESTAFF,			//
	WEAPON_ENCHANTEDSWORD,			//
	WEAPON_ENCHANTEDLANCE,			//
	WEAPON_ENCHANTEDSPEAR,			//
	WEAPON_ENCHANTEDMORNINGSTAR,		//
	WEAPON_ENCHANTEDQUARTERSTAFF,		//
	WEAPON_MIDAGGER,			//
	WEAPON_ENCHANTEDDAGGER,			//
	WEAPON_ENCHANTEDKNIFE,			//
	WEAPON_LONGSWORD,			//
	WEAPON_ENCHANTEDCLUB,			//
	WEAPON_ENCHANTEDHAMMER,			//
	WEAPON_ENCHANTEDAXE,			//
	WEAPON_ENCHANTEDPICK,			//
	WEAPON_ENCHANTEDPARRYINGDAGGER,		//
	WEAPON_SABRE,				//
	WEAPON_BATTLEHAMMER,			//
	WEAPON_BROADSWORD,			//
	WEAPON_MACE,				//
	WEAPON_ENRUNEDAXE,			//
	WEAPON_BATTLEAXE,			//
	WEAPON_PIKE,				//
	WEAPON_SWORD,				//
	WEAPON_LANCE,				//
	WEAPON_ENRUNEDSPEAR,			//
	WEAPON_SPEAR,				//
	WEAPON_MORNINGSTAR,			//
	WEAPON_QUARTERSTAFF,			//
	WEAPON_HAMMER,				//
	WEAPON_AXE,				//
	WEAPON_PICK,				//
	WEAPON_DAGGER,				//
	WEAPON_CLUB,				//
	WEAPON_PDAGGER,				//
	WEAPON_KNIFE,				//
	WEAPON_LASSO,				//
	WEAPON_NET,				//
	NUMWEAPONS
};

//
// Types of armor
//
enum {
	ARMOR_NONE,				//
	ARMOR_CLOAKOFI,				//
	ARMOR_DRAGONSCALESARMOR,		//
	ARMOR_CLOAKOFBLOOD,			//
	ARMOR_ADMANTIUMPLATEARMOR,		//
	ARMOR_ADMANTIUMSCALEARMOR,		//
	ARMOR_ADMANTIUMCHAINARMOR,		//
	ARMOR_MITHRILPLATEARMOR,		//
	ARMOR_MITHRILSCALEARMOR,		//
	ARMOR_MITHRILCHAINARMOR,		//
	ARMOR_ENCHANTEDPLATEARMOR,		//
	ARMOR_ENCHANTEDSCALEARMOR,		//
	ARMOR_ENCHANTEDCHAINARMOR,		//
	ARMOR_STEELPLATEARMOR,			//
	ARMOR_STEELSCALEARMOR,			//
	ARMOR_STEELCHAINARMOR,			//
	ARMOR_IRONPLATEARMOR,			//
	ARMOR_IRONSCALEARMOR,			//
	ARMOR_IRONCHAINARMOR,			//
	ARMOR_BPLATE,				//
	ARMOR_ENCHANTEDLEATHERARMOR,		//
	ARMOR_ENCHANTEDCLOTHARMOR,		//
	ARMOR_LEATHERARMOR,			//
	ARMOR_CLOTHARMOR,			//
	ARMOR_SHIELD,				//
	ARMOR_ASHIELD,				//
	ARMOR_MSHIELD,				//
	ARMOR_SSHIELD,				//
	ARMOR_ISHIELD,				//
	ARMOR_WSHIELD,				//
	NUMARMORS
};

//
// Types of mounts
//
enum {
	MOUNT_NONE,				//
	MOUNT_MAMM,				//
	MOUNT_ELEP,				//
	MOUNT_MOLE,				//
	MOUNT_WING,				//
	MOUNT_MFLI,				//
	MOUNT_BATTLELIZARD,
	MOUNT_CHARGER,
	MOUNT_WARLIZARD,
	MOUNT_WARHORSE,
	MOUNT_MEAG,				//
	MOUNT_MBAT,				//
	MOUNT_HUNTINGDOG,
	MOUNT_WARDOG,
	MOUNT_CAME,				//
	MOUNT_MLIZ,				//
	MOUNT_HORS,				//
	MOUNT_MWOL,				//
	MOUNT_MSPI,				//
	MOUNT_PONY,				//
	NUMMOUNTS
};

//
// Other battle items
//
enum {
	BATTLE_NONE,				//
	BATTLE_RUNESWORD,			//
	BATTLE_STAFFOFL,			//
	BATTLE_STAFFOFM,			//
	BATTLE_STAFFOFI,			//
	BATTLE_STAFFOFF,			//
	BATTLE_SOULEATER,			//
	BATTLE_ICESWORD,			//
	BATTLE_FLAMINGSWORD,			//
	BATTLE_MAGESTAFF,			//
	BATTLE_AOFI,				//
	BATTLE_CORONETOFP,			//
	BATTLE_AMULETOFP,			//
	BATTLE_STAFFOFPOWER,			//
	BATTLE_STAFFOFFLAME,			//
	BATTLE_STAFFOFCOLDNESS,			//
	BATTLE_STAFFOFACIDSHOWER,		//
	BATTLE_SHIELDSTONE,			//
	NUMBATTLEITEMS
};

//
// Types of skills.
//
enum {
	S_GEMCUTTING,
	S_MINING,				//0
	S_LUMBERJACK,				//1
	S_QUARRYING,				//2
	S_HUNTING,				//3
	S_FISHING,				//4
	S_HERBLORE,				//5
	S_SMITHING,				//6
	S_TOOLMAKING,				//7
	S_BUILDING,				//8
	S_SHIPBUILDING,				//9
	S_ENTERTAINMENT,			//10
	S_TACTICS,				//11
	S_COMBAT,				//12
	S_RIDING,				//13
	S_CROSSBOW,				//14
	S_ARCHERY,				//15
	S_STEALTH,				//16
	S_OBSERVATION,				//17
	S_HEALING,				//18
	S_SAILING,				//19
	S_FARMING,				//20
	S_RANCHING,				//21
	S_WEAPONCRAFT,				//22
	S_ARMORCRAFT,				//23
	S_ANIMALTRAINING,			//25
	S_ANIMALTAMING,				//26
	S_MONSTERTAMING,			//27
	S_COOKING,				//28
	S_MANIPULATE,				//29
	S_FORCE,				//30
	S_PATTERN,				//31
	S_SPIRIT,				//32
	S_FIRE,					//33
	S_ICE,					//34
	S_MIND,					//35
	S_EARTHQUAKE,				//36
	S_FORCE_SHIELD,				//37
	S_ENERGY_SHIELD,			//38
	S_WEATHER_SHIELD,			//39
	S_SPIRIT_SHIELD,			//40
	S_MAGICAL_HEALING,			//41
	S_GATE_LORE,				//42
	S_FARSIGHT,				//43
	S_TELEPORTATION,			//44
	S_PORTAL_LORE,				//45
	S_MIND_READING,				//46
	S_WEATHER_LORE,				//47
	S_SUMMON_WIND,				//48
	S_SUMMON_STORM,				//49
	S_SUMMON_TORNADO,			//50
	S_CALL_LIGHTNING,			//51
	S_CLEAR_SKIES,				//52
	S_EARTH_LORE,				//53
	S_WOLF_LORE,				//54
	S_BIRD_LORE,				//55
	S_DRAGON_LORE,				//56
	S_WYRM_LORE,				//57
	S_SUMMON_DRAGON,			//58
	S_SUMMON_WYRM,				//59
	S_NECROMANCY,				//60
	S_SUMMON_SKELETONS,			//61
	S_RAISE_UNDEAD,				//62
	S_SUMMON_LICH,				//63
	S_CREATE_AURA_OF_FEAR,			//64
	S_SUMMON_BLACK_WIND,			//65
	S_ENERGY_BLAST,				//66
	S_BANISH_UNDEAD,			//67
	S_DEMON_LORE,				//68
	S_SUMMON_IMPS,				//69
	S_SUMMON_DEMON,				//70
	S_SUMMON_BALROG,			//71
	S_BANISH_DEMONS,			//72
	S_ILLUSION,				//73
	S_PHANTASMAL_ENTERTAINMENT,		//74
	S_CREATE_PHANTASMAL_BEASTS,		//75
	S_CREATE_PHANTASMAL_UNDEAD,		//76
	S_CREATE_PHANTASMAL_DEMONS,		//77
	S_INVISIBILITY,				//78
	S_TRUE_SEEING,				//79
	S_DISPEL_ILLUSIONS,			//80
	S_ARTIFACT_LORE,			//81
	S_CREATE_RING_OF_INVISIBILITY,		//82
	S_CREATE_CLOAK_OF_INVULNERABILITY,	//83
	S_CREATE_STAFF_OF_FIRE,			//84
	S_CREATE_STAFF_OF_LIGHTNING,		//85
	S_CREATE_AMULET_OF_TRUE_SEEING,		//86
	S_CREATE_AMULET_OF_PROTECTION,		//87
	S_CREATE_RUNESWORD,			//88
	S_CREATE_FLAMING_SWORD,			//89
	S_CREATE_SHIELDSTONE,			//90
	S_CREATE_MAGIC_CARPET,			//91
	S_ENGRAVE_RUNES_OF_WARDING,		//92
	S_CONSTRUCT_GATE,			//93
	S_ENCHANT_WEAPONS,			//94
	S_ENCHANT_ARMOR,			//95
	S_CONSTRUCT_PORTAL,			//96
	S_CREATE_FOOD,				//97
	S_CREATE_ICE_SWORD,
	S_CREATE_SOUL_EATER,
	S_CREATE_STAFF_OF_ICE,
	S_CREATE_STAFF_OF_MIND,
	S_CREATE_CORONET_OF_PROTECTION,
	S_SCOUTING,
	S_ENCHANT_RINGS,
	S_ENCHANT_AMULETS,
	S_CREATE_CHARMS,
	NSKILLS
};

//
// Types of special attacks
//
enum {
	SPECIAL_NONE_DUMMY,			//
	SPECIAL_FIREBALL,			//
	SPECIAL_ICECONE,			//
	SPECIAL_MINDSTRIKE,			//
	SPECIAL_HELLFIRE,			//
	SPECIAL_CAUSEFEAR,			//
	SPECIAL_LSTRIKE,			//
	SPECIAL_MINDBLAST,			//
	SPECIAL_EARTHQUAKE,			//
	SPECIAL_TRAMPLING,			//
	SPECIAL_FORCE_SHIELD,			//
	SPECIAL_ENERGY_SHIELD,			//
	SPECIAL_WEATHER_SHIELD,			//
	SPECIAL_SPIRIT_SHIELD,			//
	SPECIAL_DISPEL_ILLUSIONS,		//
	SPECIAL_SUMMON_STORM,			//
	SPECIAL_TORNADO,			//
	SPECIAL_BLACK_WIND,			//
	SPECIAL_ENERGY_BLAST,			//
	SPECIAL_BANISH_UNDEAD,			//
	SPECIAL_BANISH_DEMONS,			//
	SPECIAL_FIREBREATH,			//
	SPECIAL_POISONBREATH,			//
	SPECIAL_ICEBREATH,			//
	SPECIAL_CAMEL_FEAR,			//
	SPECIAL_INVULNERABILITY,		//
	SPECIAL_MAGESTAFF,			//
	SPECIAL_ACIDSHOWER,			//
	NUMSPECIALS
};

//
// Types of objects.
//
enum {
	O_DUMMY,				//0
	O_ROWINGBOAT,				//1
	O_LONGBOAT,				//2
	O_PINK,  				//3
	O_GALLEON,				//4
	O_WARGALLEY,				//5
	O_WARGALLEON,				//6
	O_AIRSHIP,				//7
	O_HERMITSHUT,				//8
	O_TOWER,				//9
	O_GRANDTOWER,				//10
	O_STOCKADE,				//11
	O_GRANDSTOCKADE,			//12
	O_FORT,					//13
	O_GRANDFORT,				//14
	O_CASTLE,				//15
	O_GRANDCASTLE,				//16
	O_CITADEL,				//17
	O_GRANDCITADEL,				//18
	O_FORTRESS,				//19
	O_GRANDFORTRESS,			//20
	O_MAGICALTOWER,				//21
	O_MAGICALCASTLE,			//22
	O_MAGICALFORTRESS,			//23
	O_PALACE,				//24
	O_CPALACE,				//25
	O_CLOUDPALACE,				//26
	O_HTOWER,				//27
	O_HPTOWER,				//28
	O_NGUILD,				//29
	O_AGUILD,				//30
	O_GDCLIFFS,				//31
	O_EDCLIFFS,				//32
	O_SHAFT,				//33
	O_GREENLAIR,				//34
	O_BROWNLAIR,				//35
	O_BLUELAIR,				//36
	O_REDLAIR,				//37
	O_WHITELAIR,				//38
	O_BLACKLAIR,				//39
	O_RUIN,					//40
	O_CAVE,					//41
	O_DEMONPIT,				//42
	O_CRYPT,				//43
	O_ISLE,					//44
	O_DERELICT,				//45
	O_PEATBOG,				//46
	O_WHIRL,				//47
	O_MAGETOWER,				//48
	O_DARKTOWER,				//49
	O_GIANTCASTLE,				//50
	O_ILAIR,				//51
	O_ICECAVE,				//52
	O_THICKET,				//53
	O_PYRAMID,				//54
	O_BKEEP,				//55
	O_ATEMPLE,				//56
	O_TEMPLE,				//57
	O_HUT,					//58
	O_HOUSE,				//59
	O_AQUEDUCT,				//60
	O_INN,					//61
	O_FAIR,					//62
	O_FARM,					//63
	O_MILL,					//64
	O_MUSHROOMFARM,				//65
	O_IRRIGATION,				//66
	O_VINEYARD,				//67
	O_WINEPRESS,				//68
	O_COTTONPLANTATION,			//69
	O_COTTONCOLLECTORS,			//70
	O_TRUFFLESPLANTATION,			//71
	O_BOARPEN,				//72
	O_TOBACCOPLANTATION,			//73
	O_HORTICULTURE,				//74
	O_SHEEPFARM,				//75
	O_SHEEPDIP,				//76
	O_WOOLINGERFARM,			//77
	O_WOOLINGERDIP,				//78
	O_RANCH,				//79
	O_SLAUGHTERHOUSE,			//80
	O_LIZARDRANCH,				//81
	O_LIZARDSLAUGHTERHOUSE,			//82
	O_SHEPHERDHUT,				//83
	O_MENAGERIE,				//84
	O_FISHINGFLEET,				//85
	O_JETTY,				//86
	O_ARTIFICIALREEF,			//87
	O_DIVINGFLOATS,				//88
	O_WHALINGFLEET,				//89
	O_MINE,					//90
	O_FURNACE,				//91
	O_GEMMINE,				//92
	O_GEMAPPRAISER,				//93
	O_MITHRILMINE,				//94
	O_PROSPECTORSHUT,			//95
	O_ADMANTIUMMINE,			//96
	O_GOLDMINE,				//97
	O_TREENURSERY,				//98
	O_TIMBERYARD,				//99
	O_TREETENDERSHUT,			//100
	O_SAWINGMILL,				//101
	O_YEWGROVE,				//102
	O_QUARRY,				//103
	O_STONECUTTERSHUT,			//104
	O_ROOTSTONEQUARRY,			//105
	O_STONEMASONSHUT,			//106
	O_CORESTONEQUARRY,			//107
	O_HUNTINGHUT,				//108
	O_HUNTINGSTAND,				//109
	O_TRAPPINGHUT,				//110
	O_CAGETRAP,				//111
	O_WALKWAY,				//112
	O_GASTANK,				//113
	O_TRAPPINGLODGE,			//114
	O_HERBGARDEN,				//115
	O_HERBALISTSTORE,			//116
	O_FUNGUSGARDEN,				//117
	O_DRYINGSHED,				//118
	O_DRUIDCIRCLE,				//119
	O_PONYSTABLE,				//120
	O_WOLFPEN,				//121
	O_SPIDERSTABLE,				//122
	O_STABLE,				//123
	O_CAMELSTABLE,				//124
	O_LIZARDSTABLE,				//125
	O_EYRIE,				//126
	O_BATCAVE,				//127
	O_ELEPHANTSTABLE,			//128
	O_MAMMOTHSTABLE,			//129
	O_MOLEBURROW,				//130
	O_WINGEDHORSESTABLE,			//131
	O_FLYINGLIZARDSTABLE,			//132
	O_WARGPIT,				//133
	O_TOURNAMENTCOURSE,			//134
	O_TRAININGPIT,				//135
	O_HARPYNEST,				//136
	O_BREEDINGPIT,				//137
	O_CHIMERAROOST,				//138
	O_MAMMOTHWARSCHOOL,			//139
	O_VOLCANICPOOL,				//140
	O_KENNEL,				//141
	O_TOURNAMENTPARCOURS,			//142
	O_TRAININGPEN,				//143
	O_VIRGINARY,				//144
	O_DRAKENSTEIN,				//145
	O_GRIFFONSTABLE,			//146
	O_ELEPHANTWARSCHOOL,			//147
	O_FIREDRAKECLIFF,			//148
	O_TAVERN,				//149
	O_JOINER,				//150
	O_SMITHY,				//151
	O_WEAPONFORGE,				//152
	O_ARMORFORGE,				//153
	O_TEAMTRAINER,				//154
	O_APOTHECARY,				//155
	O_PELTMONGER,				//156
	O_SCULPTOR,				//157
	O_JEWELER,				//158
	O_FISHERY,				//159
	O_FARMHOUSE,				//160
	O_RANCHHOUSE,				//161
	O_CHANDLER,				//162
	O_RUNEMASTER,				//163
	O_ROADN,				//164
	O_ROADNW,				//165
	O_ROADNE,				//166
	O_ROADSW,				//167
	O_ROADSE,				//168
	O_ROADS,				//169
	O_RAFT,
	O_TEPUKE,
	O_SLOOP,
	O_CUTTER,
	O_SCHOONER,
	O_SNOW,
	O_JUNK,
	O_DHOW,
	O_BRIG,
	O_TARTAN,
	O_CARAVEL,
	O_CARRACK,
	O_GALLEY,
	O_COG,
	O_FLOATINGFORTRESS,
	O_GHOSTSHIP,
	O_BALLOON,
	O_SIGNPOST,
	O_ELEFANTWARSCHOOL,
	O_BEHEMOTHWARSCHOOL,
	NOBJECTS
};

//
// Types of terrain
//
/* ARegion Types */
enum {
        //standard terrains
	R_NEXUS,				//11
	R_OCEAN,				//0
	R_PLAIN,				//1
	R_TUNDRA,				//7
	R_DESERT,				//6
	R_FOREST,				//2
	R_HILL,				//31
	R_MOUNTAIN,				//3
	//rich terrains
	R_LAKE,		      
	R_RICHTUNDRA,		
	R_OASIS,			
	R_MYSTFOREST,		
	R_RICHHILL,		
	R_RICHMOUNTAIN,		

	//obsolete but needed by aregion.cpp
	R_CE_GDLAKE,
	R_T_GROTTO1,
	R_CE_WASTELAND,
	R_T_HILL1,
	R_SWAMP,
	R_JUNGLE,
	R_T_MYSTFOREST1,
	R_CAVERN,
	R_UFOREST,
	R_TUNNELS,
	R_CE_GDDFOREST,
	R_CE_GDDCAVERN,
	R_CE_DTUNNELS,
	R_T_MINES1,
	R_T_CHAMBER1,
	R_T_DESERT1,
	R_T_DESERT2,
	R_T_DESERT3,
	R_CE_GDDESERT,
	R_CE_GDDESERT1,
	R_CE_EVDESERT,
	R_CE_EVDESERT1,
	R_CE_WASTELAND1,
	R_CE_GRANITE,
	R_CE_BASALT,

	//needed again
	R_COASTAL,
	R_NUM
};

// Types of effects
enum {
	EFFECT_DAZZLE,				//
	EFFECT_FEAR,				//
	EFFECT_STORM,				//
	NUMEFFECTS
};

// Types of ranges
enum {
	RANGE_TELEPORT,				//
	RANGE_PORTAL_LORE,			//
	RANGE_FARSIGHT,				//
	RANGE_WEATHER_LORE,			//
	RANGE_CLEAR_SKIES,			//
	NUMRANGES
};

enum {
  SUMMON_BALROG,				//
  SUMMON_DEMON,					//
  SUMMON_IMP,					//
  SUMMON_LICH,					//
  SUMMON_UNDEAD,				//
  SUMMON_SKELETON,				//
  SUMMON_WOLF,					//
  SUMMON_BIRD,					//
  SUMMON_DRAGON,				//
};

#endif
