// START A3HEADER
//
// This source file is part of the Atlantis PBM game program.
// Copyright (C) 1995-1999 Geoff Dunbar
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation; either version 2
// of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program, in the file license.txt. If not, write
// to the Free Software Foundation, Inc., 59 Temple Place - Suite 330,
// Boston, MA 02111-1307, USA.
//
// See the Atlantis Project web page for details:
// http://www.prankster.com/project
//
// END A3HEADER
//
#ifndef RULES_H
#define RULES_H

//
// The items
//
enum {
	I_LEADERS,				//0
	I_MAN,					//1
	I_TLHUMAN,				//2
	I_TRHUMAN,				//3
	I_TLVIKING,				//4
	I_TRVIKING,				//5
	I_TLDERVISH,				//6
	I_TRNOMAD,				//7
	I_TLBARBARIAN,				//8
	I_TRBARBARIAN,				//9
	I_TLHIGHLANDER,				//10
	I_TRCLANSMAN,				//11
	I_TLIMPERIAL,				//12
	I_TRIMPERIAL,				//13
	I_TLTRIBESMAN,				//14
	I_TRTRIBESMAN,				//15
	I_TLFFOLK,				//16
	I_TRFFOLK,				//17
	I_TLCAJUN,				//18
	I_TRLIZARDMAN,				//19
	I_TLLOWLANDER,				//20
	I_TRHALFING,				//21
	I_TLELF,				//22
	I_TRHALFELF,				//23
	I_TLDARKMAN,				//24
	I_TRDARKMAN,				//25
	I_TLGNOME,				//26
	I_TRGNOME,				//27
	I_TLDWARF,				//28
	I_TRDWARF,				//29
	I_TLHOBGOBLIN,				//30
	I_TRGOBLIN,				//31
	I_TLBUCCANEER,				//32
	I_TRBUCCANEER,				//33
	I_TLSANDLING,				//34
	I_TRSANDLING,				//35
	I_TLTROLL,				//36
	I_TRGNOLL,				//37
	I_TLURUK,				//38
	I_TRORC,				//39
	I_TLBLACKKEEP,				//40
	I_TRBLACKKEEP,				//41
	I_TLHEADHUNTER,				//42
	I_TRHEADHUNTER,				//43
	I_TLOGRE,				//44
	I_TROGRE,				//45
	I_TLSERPENTPEOPLE,			//46
	I_TRSERPENTPEOPLE,			//47
	I_TLREPUBLICAN,				//48
	I_TRREPUBLICAN,				//49
	I_TLAMAZON,				//50
	I_TRAMAZON,				//51
	I_TLMINOTAUR,				//52
	I_TRMINOTAUR,				//53
	I_TLDROW,				//54
	I_TRDROW,				//55
	I_TLDUERGAR,				//56
	I_TRDUERGAR,				//57
	I_SILVER,				//58
	I_GRAIN,				//59
	I_MUSHROOM,				//60
	I_GRAPES,				//61
	I_COTTON,				//62
	I_TRUFFLES,				//63
	I_TOBACCO,				//64
	I_DYEPLANT,				//65
	I_SHEEP,				//66
	I_WOOLINGER,				//67
	I_LIVESTOCK,				//68
	I_LIZARD,				//69
	I_POINTYEAREDSHEEP,			//70
	I_SPIDER,				//71
	I_FISH,					//72
	I_MUSSELS,				//73
	I_WHALE,				//74
	I_IRON,					//75
	I_ROUGHGEM,				//76
	I_MITHRIL,				//77
	I_ADMANTIUM,				//78
	I_GOLD,					//79
	I_WOOD,					//80
	I_IRONWOOD,				//81
	I_YEW,					//82
	I_STONE,				//83
	I_ROOTSTONE,				//84
	I_CORESTONE,				//85
	I_GAME,					//86
	I_FURREDANIMAL,				//87
	I_MARSHGAS,				//88
	I_PELTANIMAL,				//89
	I_HERB,					//90
	I_FUNGUS,				//91
	I_MEDICINEPLANT,			//92
	//Mounts
	I_PONY,					//93
	I_GIANTWOLF,				//94
	I_GIANTSPIDER,				//95
	I_HORSE,				//96
	I_CAMEL,				//97
	I_GIANTLIZARD,				//98
	I_GIANTEAGLE,				//99
	I_GIANTBAT,				//100
	I_ELEPHANT,				//101
	I_MAMMOTH,				//102
	I_GIANTMOLE,				//103
	I_WINGEDHORSE,				//104
	I_FLYINGLIZARD,				//105
	//Mounts for evil races
	I_WARG,					//106
	I_WARHORSE,				//107
	I_WARLIZARD,				//108
	I_HARPY,				//109
	I_GIANTCENTIPEDE,			//110
	I_CHIMERA,				//111
	I_WARMAMMOTH,				//112
	I_FIRELIZARD,				//113
	//Mounts for good races
	I_HUNTINGDOG,				//114
	I_CHARGER,				//115
	I_BATTLELIZARD,				//116
	I_UNICORN,				//117
	I_DRAKE,				//118
	I_GRIFFON,				//119
	I_WARELEPHANT,				//120
	I_FIREDRAKE,				//121
	//trade goods
	I_MEAT,					//122
	I_HIDE,					//123
	I_RATION,				//124
	I_FOOD,					//125
	I_DELICATESSEN,				//126
	I_BEER,					//127
	I_WINE,					//128
	I_CLOTHES,				//129
	I_PARFAIT,				//130
	I_CIGARS,				//131
	I_DYE,					//132
	I_WOOL,					//133
	I_CASHMERE,				//134
	I_POISON,				//135
	I_GARMENT,				//136
	I_PEARL,				//137
	I_OIL,					//138
	I_CHAIN,				//139
	I_GEM,					//140
	I_JEWELRY,				//141
	I_MIRROR,				//142
	I_ORNAMENT,				//143
	I_NECKLACE,				//144
	I_FURNITURE,				//145
	I_STRONGBOX,				//146
	I_IDOL,					//147
	I_STATUE,				//148
	I_FIGURINE,				//149
	I_TALISMAN,				//150
	I_FUR,					//151
	I_PELT,					//152
	I_FURCOAT,				//153
	I_PELTCOAT,				//154
	I_PERFUME,				//155
	I_HEALINGDRAFT,				//156
	I_MEDICINE,				//157
	I_HEALINGPOTION,			//158
	//tools
	I_SPINNINGWHEEL,			//159
	I_BARREL,				//160
	I_WAGON,				//161
	I_OXCART,				//162
	I_CARRIAGE,				//163
	I_LIZARDWAGON,				//164
	I_LIZARDCART,				//165
	I_LIZARDCARRIAGE,			//166
	I_PRESS,				//167
	I_LOOM,					//168
	I_HARP,					//169
	I_GLIDER,				//170
	I_NET,					//171
	I_LASSO,				//172
	I_BAG,					//173
	I_CUTLERY,				//174
	I_SAW,					//175
	I_CHISEL,				//176
	//weapons
	I_JAVELIN,				//177
	I_ENCHANTEDJAVELIN,			//178
	I_LIGHTCROSSBOW,			//179
	I_ENHANTEDLIGHTCROSSBOW,		//180
	I_CROSSBOW,				//181
	I_HEAVYCROSSBOW,			//182
	I_SHORTBOW,				//183
	I_ENCHANTEDSHORTBOW,			//184
	I_BOW,					//185
	I_LONGBOW,				//186
	I_PICK,					//187
	I_ENCHANTEDPICK,			//188
	I_SPEAR,				//189
	I_ENCHANTEDSPEAR,			//190
	I_PIKE,					//191
	I_ENCHANTEDPIKE,			//192
	I_LANCE,				//193
	I_ENCHANTEDLANCE,			//194
	I_HALBERD,				//195
	I_ENRUNEDSPEAR,				//196
	I_FIRESPEAR,				//197
	I_ICESPEAR,				//198
	I_QUARTERSTAFF,				//199
	I_ENCHANTEDQUARTERSTAFF,		//200
	I_BATTLESTAFF,				//201
	I_MAGESTAFF,				//202
	I_CLUB,					//203
	I_ENCHANTEDCLUB,			//204
	I_MACE,					//205
	I_ENCHANTEDMACE,			//206
	I_BATTLEMACE,				//207
	I_WARMACE,				//208
	I_HAMMER,				//209
	I_ENCHANTEDHAMMER,			//210
	I_MORNINGSTAR,				//211
	I_ENCHANTEDMORNINGSTAR,			//212
	I_BATTLEHAMMER,				//213
	I_ENCHANTEDBATTLEHAMMER,		//214
	I_SKULLCRUSHER,				//215
	I_AXE,					//216
	I_ENCHANTEDAXE,				//217
	I_BATTLEAXE,				//218
	I_ENCHANTEDBATTLEAXE,			//219
	I_CLEAVER,				//220
	I_ENRUNEDAXE,				//221
	I_WARAXE,				//222
	I_SWIFTAXE,				//223
	I_KNIFE,				//224
	I_ENCHANTEDKNIFE,			//225
	I_DAGGER,				//226
	I_ENCHANTEDDAGGER,			//227
	I_PARRYINGDAGGER,			//228
	I_ENCHANTEDPARRYINGDAGGER,		//229
	I_MITHRILDAGGER,			//230
	I_ADMANTIUMDAGGER,			//231
	I_SABRE,				//232
	I_ENCHANTEDSABRE,			//233
	I_EPEE,					//234
	I_FOIL,					//235
	I_SWORD,				//236
	I_ENCHANTEDSWORD,			//237
	I_BROADSWORD,				//238
	I_ENCHANTEDBROADSWORD,			//239
	I_LONGSWORD,				//240
	I_ENCHANTEDLONGSWORD,			//241
	I_MITHRILSWORD,				//242
	I_MITHRILBROADSWORD,			//243
	I_MITHRILLONGSWORD,			//244
	I_ADMANTIUMSWORD,			//245
	I_ADMANTIUMBROADSWORD,			//246
	I_ADMANTIUMLONGSWORD,			//247
	I_FLAMINGSWORD,				//248
	I_RUNESWORD,				//249
	//armour
	I_SHIELD,				//250
	I_CLOTHARMOR,				//251
	I_LEATHERARMOR,				//252
	I_BARBARIANPLATE,			//253
	I_IRONCHAINARMOR,			//254
	I_IRONSCALEARMOR,			//255
	I_IRONPLATEARMOR,			//256
	I_MITHRILCHAINARMOR,			//257
	I_MITHRILSCALEARMOR,			//258
	I_MITHRILPLATEARMOR,			//259
	I_ADMANTIUMCHAINARMOR,			//260
	I_ADMANTIUMSCALEARMOR,			//261
	I_ADMANTIUMPLATEARMOR,			//262
	I_DRAGONSCALESARMOR,			//263
	I_CLOAKOFINVULNERABILITY,		//264
	I_ENCHANTEDCLOTHARMOR,			//265
	I_ENCHANTEDLEATHERARMOR,		//266
	I_ENCHANTEDCHAINARMOR,			//267
	I_ENCHANTEDSCALEARMOR,			//268
	I_ENCHANTEDPLATEARMOR,			//269
	//magic items
	I_BOOTS,				//270
	I_AMULETOFI,				//271
	I_RINGOFI,				//272
	I_STAFFOFF,				//273
	I_STAFFOFL,				//274
	I_AMULETOFTS,				//275
	I_AMULETOFP,				//276
	I_SHIELDSTONE,				//277
	I_MCARPET,				//278
	I_PORTAL,				//279
	//monsters
	I_IDRAGON,				//280
	I_IWOLF,				//281
	I_IEAGLE,				//282
	I_ISKELETON,				//283
	I_IUNDEAD,				//284
	I_ILICH,				//285
	I_IIMP,					//286
	I_IDEMON,				//287
	I_IBALROG,				//288
	I_EAGLE,				//289
	I_STEELDRAGON,				//290
	I_COPPERDRAGON,				//291
	I_BRONZEDRAGON,				//292
	I_SILVERDRAGON,				//293
	I_GOLDENDRAGON,				//294
	I_WOLF,					//295
	I_CROW,					//296
	I_MOUNTAINLION,				//297
	I_GIANTRAT,				//298
	I_SNAKE,				//299
	I_LION,					//300
	I_ICEWOLF,				//301
	I_POISONSPIDER,				//302
	I_FANGEDLIZARD,				//303
	I_CRAWLER,				//304
	I_LIVINGTREE,				//305
	I_GRIZZLYBEAR,				//306
	I_ROC,					//307
	I_SWAMPCREATURE,			//308
	I_TIGER,				//309
	I_GIANTSCORPION,			//310
	I_POLARBEAR,				//311
	I_GIANTSQUID,				//312
	I_BUGBEAR,				//313
	I_MAULER,				//314
	I_TUNNELWORM,				//315
	I_GREENDRAGON,				//316
	I_BROWNDRAGON,				//317
	I_BLUEDRAGON,				//318
	I_REDDRAGON,				//319
	I_WHITEDRAGON,				//320
	I_BLACKDRAGON,				//321
	I_BOGTHING,				//322
	I_HYDRA,				//323
	I_SPHINX,				//324
	I_KRAKEN,				//325
	I_ILLYRTHID,				//326
	I_THIEF,				//327
	I_HIGHWAYMAN,				//328
	I_GOBLIN,				//329
	I_SKELETON,				//330
	I_IMP,					//331
	I_PIRATE,				//332
	I_MERFOLK,				//333
	I_MUTANT,				//334
	I_CENTAUR,				//335
	I_KOBOLD,				//336
	I_WILDMAN,				//337
	I_SANDLING,				//338
	I_DROWWARRIOR,				//339
	I_EVILWARRIOR,				//340
	I_OGRE,					//341
	I_YETI,					//342
	I_TROLL,				//343
	I_ETTIN,				//344
	I_UNDEAD,				//345
	I_DEMON,				//346
	I_BALROG,				//347
	I_LICH,					//348
	I_STORMGIANT,				//349
	I_CLOUDGIANT,				//350
	I_EVILSORCERER,				//351
	I_EVILMAGICIAN,				//352
	I_DARKPRIEST,				//353
	//monster spoils
	I_DRAGONSCALES,				//354
	I_DRAGONBLOOD,				//355
	I_SWAMPCRYSTAL,				//356
	I_HYDRABLOOD,				//357
	I_TOME,					//358
	I_RUBY,					//359
	I_KRAKENEYE,				//360
	I_ILLYRTHIDBRAIN,			//361
	I_BEARCLAWS,				//362
	I_ROCFEATHER,				//363
	I_SLIME,				//364
	I_SQUIDBEAK,				//365
	I_ACID,					//366
	I_EGG,					//367
	I_RATTAIL,				//368
	// ceran
	I_SLAVE,				//369
	I_MERCENARY,				//370
	I_LHIGHMAN,				//371
	I_HIGHMAN,				//372
	I_LDARKMAN,				//373
	I_DARKMAN,				//374
	I_LHIGHLANDER,				//375
	I_HIGHLANDER,				//376
	I_LBARBARIAN,				//377
	I_BARBARIAN,				//378
	I_LPLAINSMAN,				//379
	I_PLAINSMAN,				//380
	I_LHELOT,				//381
	I_HELOT,				//382
	I_LBEARTRIBE,				//383
	I_BEARTRIBE,				//384
	I_LNORTHMAN,				//385
	I_NORTHMAN,				//386
	I_LGYPSY,				//387
	I_GYPSY,				//388
	I_LWAGONFOLK,				//389
	I_WAGONFOLK,				//390
	I_LTRIBESMAN,				//391
	I_TRIBESMAN,				//392
	I_LHEADHUNTER,				//393
	I_HEADHUNTER,				//394
	I_LWOODSMAN,				//395
	I_WOODSMAN,				//396
	I_LAMAZON,				//397
	I_AMAZON,				//398
	I_LHILLMAN,				//399
	I_HILLMAN,				//400
	I_LHALFORC,				//401
	I_HALFORC,				//402
	I_LCAVEDWELLER,				//403
	I_CAVEDWELLER,				//404
	I_LTROGLODYTE,				//405
	I_TROGLODYTE,				//406
	I_LDEEPFFOLK,				//407
	I_DEEPFFOLK,				//408
	I_LNIGHTSTALKER,			//409
	I_NIGHTSTALKER,				//410
	I_LCOMMONMAN,				//411
	I_COMMONMAN,				//412
	I_LGNOLL,				//413
	I_GNOLL,				//414
	I_LHILLDWARF,				//415
	I_HILLDWARF,				//416
	I_LMOUNTAINDWARF,			//417
	I_MOUNTAINDWARF,			//418
	I_LICEDWARF,				//419
	I_ICEDWARF,				//420
	I_LDESERTDWARF,				//421
	I_DESERTDWARF,				//422
	I_LUNDERDWARF,				//423
	I_UNDERDWARF,				//424
	I_LDARKDWARF,				//425
	I_DARKDWARF,				//426
	I_LDEEPDWARF,				//427
	I_DEEPDWARF,				//428
	I_LGULLYDWARF,				//429
	I_GULLYDWARF,				//430
	I_LWOODELF,				//431
	I_WOODELF,				//432
	I_LSEAELF,				//433
	I_SEAELF,				//434
	I_LHIGHELF,				//435
	I_HIGHELF,				//436
	I_LTRIBALELF,				//437
	I_TRIBALELF,				//438
	I_LNIGHTELF,				//439
	I_NIGHTELF,				//440
	I_LDRAGONLORD,				//441
	I_DRAGONLORD,				//442
	I_LDARKELF,				//443
	I_DARKELF,				//444
	I_LDEATHWALKER,				//445
	I_DEATHWALKER,				//446
	I_LORC,					//447
	I_ORC,					//448
	I_LURUK,				//449
	I_URUK,					//450
	I_LGOBLINMAN,				//451
	I_GOBLINMAN,				//452
	I_LOGREMAN,				//453
	I_OGREMAN,				//454
	I_LHOBBIT,				//455
	I_HOBBIT,				//456
	I_LGNOME,				//457
	I_GNOME,				//458
	I_LMINOTAUR,				//459
	I_MINOTAUR,				//460
	I_LLIZARDMAN,				//461
	I_LIZARDMAN,				//462
	I_LFAIRY,				//463
	I_FAIRY,				//464
	I_LTITAN,				//465
	I_TITAN,				//466
	I_STEELDRAGON_S,			//467
	I_COPPERDRAGON_S,			//468
	I_BRONZEDRAGON_S,			//469
	I_SILVERDRAGON_S,			//470
	I_GOLDENDRAGON_S,			//471
	I_STEELDRAGON_O,			//472
	I_COPPERDRAGON_O,			//473
	I_BRONZEDRAGON_O,			//474
	I_SILVERDRAGON_O,			//475
	I_GOLDENDRAGON_O,			//476
	I_STEELDRAGON_A,			//477
	I_COPPERDRAGON_A,			//478
	I_BRONZEDRAGON_A,			//479
	I_SILVERDRAGON_A,			//480
	I_GOLDENDRAGON_A,			//481
	I_STEELDRAGON_B,			//482
	I_COPPERDRAGON_B,			//483
	I_BRONZEDRAGON_B,			//484
	I_SILVERDRAGON_B,			//485
	I_GOLDENDRAGON_B,			//486
	I_GREENDRAGON_S,			//487
	I_BROWNDRAGON_S,			//488
	I_BLUEDRAGON_S,				//489
	I_REDDRAGON_S,				//490
	I_WHITEDRAGON_S,			//491
	I_BLACKDRAGON_S,			//492
	I_GREENDRAGON_O,			//493
	I_BROWNDRAGON_O,			//494
	I_BLUEDRAGON_O,				//495
	I_REDDRAGON_O,				//496
	I_WHITEDRAGON_O,			//497
	I_BLACKDRAGON_O,			//498
	I_GREENDRAGON_A,			//499
	I_BROWNDRAGON_A,			//500
	I_BLUEDRAGON_A,				//501
	I_REDDRAGON_A,				//502
	I_WHITEDRAGON_A,			//503
	I_BLACKDRAGON_A,			//504
	I_GREENDRAGON_B,			//505
	I_BROWNDRAGON_B,			//506
	I_BLUEDRAGON_B,				//507
	I_REDDRAGON_B,				//508
	I_WHITEDRAGON_B,			//509
	I_BLACKDRAGON_B,			//510
	I_ZOMBIE,				//511
	I_RAT,					//512
	I_ANIMATEDTREE,				//513
	I_WILLOWWISP,				//514
	I_CARNIVOROUSPLANT,			//515
	I_KILLERLION,				//516
	I_LONELYCROW,				//517
	I_POISONSNAKE,				//518
	I_WILDBOAR,				//519
	I_LONELYWOLF,				//520
	I_LONELYFANGEDLIZARD,			//521
	I_LONELYPOISONSPIDER,			//522
	I_LONELYCRAWLER,			//523
	I_LONELYEVILWARRIOR,			//524
	I_ROBBER,				//525
	I_BATTLESPEAR,				//526
	I_WARSPEAR,				//527
	I_BARDICHE,				//528
	I_BATTLELANCE,				//529
	I_WARLANCE,				//530
	I_WARSTAFF,				//531
	I_TRISTAR,				//532
	I_EVENINGSTAR,				//533
	I_WARHAMMER,				//534
	I_RINGOFWARDING,			//535
	I_HHIGHMAN,				//536
	I_HDARKMAN,				//537
	I_HHIGHLANDER,				//538
	I_HBARBARIAN,				//539
	I_HPLAINSMAN,				//540
	I_HHELOT,				//541
	I_HBEARTRIBE,				//542
	I_HNORTHMAN,				//543
	I_HGYPSY,				//544
	I_HWAGONFOLK,				//545
	I_HTRIBESMAN,				//546
	I_HHEADHUNTER,				//547
	I_HWOODSMAN,				//548
	I_HAMAZON,				//549
	I_HHILLMAN,				//550
	I_HHALFORC,				//551
	I_HCAVEDWELLER,				//552
	I_HTROGLODYTE,				//553
	I_HDEEPFFOLK,				//554
	I_HNIGHTSTALKER,			//555
	I_HCOMMONMAN,				//556
	I_HGNOLL,				//557
	I_HHILLDWARF,				//558
	I_HMOUNTAINDWARF,			//559
	I_HUNDERDWARF,				//560
	I_HDARKDWARF,				//561
	I_HDEEPDWARF,				//562
	I_HGULLYDWARF,				//563
	I_HWOODELF,				//564
	I_HSEAELF,				//565
	I_HHIGHELF,				//566
	I_HTRIBALELF,				//567
	I_HNIGHTELF,				//568
	I_HDRAGONLORD,				//569
	I_HDARKELF,				//570
	I_HDEATHWALKER,				//571
	I_HORC,					//572
	I_HURUK,				//573
	I_HGOBLINMAN,				//574
	I_HOGREMAN,				//575
	I_HHOBBIT,				//576
	I_HGNOME,				//577
	I_HMINOTAUR,				//578
	I_HLIZARDMAN,				//579
	I_BLUECRYSTAL,				//580
	I_REDCRYSTAL,				//581
	I_YELLOWCRYSTAL,			//582
	I_ORANGECRYSTAL,			//583
	I_GREENCRYSTAL,				//584
	I_VIOLETCRYSTAL,			//585
	I_WHITECRYSTAL,				//586
	I_BLACKCRYSTAL,				//587
	I_BLUEPOWERCRYSTAL,			//588
	I_REDPOWERCRYSTAL,			//589
	I_YELLOWPOWERCRYSTAL,			//590
	I_ORANGEPOWERCRYSTAL,			//591
	I_GREENPOWERCRYSTAL,			//592
	I_VIOLETPOWERCRYSTAL,			//593
	I_WHITEPOWERCRYSTAL,			//594
	I_BLACKPOWERCRYSTAL,			//595
	I_RING,					//596
	I_DESERTDRAKE,				//597
	I_SWAMPDRAKE,				//598
	I_CAVEDRAKE,				//599
	I_RAINBOWDRAKE,				//600
	I_LHORSEMAN,				//601
	I_HORSEMAN,				//602
	I_HHORSEMAN,				//603
	I_LEASTERLING,				//604
	I_EASTERLING,				//605
	I_HEASTERLING,				//606
	I_RAINBOWDAGGER,			//607
	I_DARKSWORD,				//608
	I_STARAXE,				//609
	I_WSHIELD,				//610
	I_ISHIELD,				//611
	I_MSHIELD,				//612
	I_ASHIELD,				//613
	NITEMS
};

//
// Types of men.
//
enum {
	MAN_NONE,				//0
	MAN_LEADER,				//1
	MAN_MAN,				//2
	MAN_TLHUMAN,				//3
	MAN_TRHUMAN,				//4
	MAN_TLVIKING,				//5
	MAN_TRVIKING,				//6
	MAN_TLDERVISH,				//7
	MAN_TRNOMAD,				//8
	MAN_TLBARBARIAN,			//9
	MAN_TRBARBARIAN,			//10
	MAN_TLHIGHLANDER,			//11
	MAN_TRCLANSMAN,				//12
	MAN_TLIMPERIAL,				//13
	MAN_TRIMPERIAL,				//14
	MAN_TLTRIBESMAN,			//15
	MAN_TRTRIBESMAN,			//16
	MAN_TLFFOLK,				//17
	MAN_TRFFOLK,				//18
	MAN_TLCAJUN,				//19
	MAN_TRLIZARDMAN,			//20
	MAN_TLLOWLANDER,			//21
	MAN_TRHALFING,				//22
	MAN_TLELF,				//23
	MAN_TRHALFELF,				//24
	MAN_TLDARKMAN,				//25
	MAN_TRDARKMAN,				//26
	MAN_TLGNOME,				//27
	MAN_TRGNOME,				//28
	MAN_TLDWARF,				//29
	MAN_TRDWARF,				//30
	MAN_TLHOBGOBLIN,			//31
	MAN_TRGOBLIN,				//32
	MAN_TLBUCCANEER,			//33
	MAN_TRBUCCANEER,			//34
	MAN_TLSANDLING,				//35
	MAN_TRSANDLING,				//36
	MAN_TLTROLL,				//37
	MAN_TRGNOLL,				//38
	MAN_TLURUK,				//39
	MAN_TRORC,				//40
	MAN_TLBLACKKEEP,			//41
	MAN_TRBLACKKEEP,			//42
	MAN_TLHEADHUNTER,			//43
	MAN_TRHEADHUNTER,			//44
	MAN_TLOGRE,				//45
	MAN_TROGRE,				//46
	MAN_TLSERPENTPEOPLE,			//47
	MAN_TRSERPENTPEOPLE,			//48
	MAN_TLREPUBLICAN,			//49
	MAN_TRREPUBLICAN,			//50
	MAN_TLAMAZON,				//51
	MAN_TRAMAZON,				//52
	MAN_TLMINOTAUR,				//53
	MAN_TRMINOTAUR,				//54
	MAN_TLDROW,				//55
	MAN_TRDROW,				//56
	MAN_TLDUERGAR,				//57
	MAN_TRDUERGAR,				//58
	MAN_SLAVE,				//59
	MAN_MERC,				//60
	MAN_LHIGHMAN,				//61
	MAN_HIGHMAN,				//62
	MAN_LDARKMAN,				//63
	MAN_DARKMAN,				//64
	MAN_LHIGHLANDER,			//65
	MAN_HIGHLANDER,				//66
	MAN_LBARBARIAN,				//67
	MAN_BARBARIAN,				//68
	MAN_LPLAINSMAN,				//69
	MAN_PLAINSMAN,				//70
	MAN_LHELOT,				//71
	MAN_HELOT,				//72
	MAN_LBEARTRIBE,				//73
	MAN_BEARTRIBE,				//74
	MAN_LNORTHMAN,				//75
	MAN_NORTHMAN,				//76
	MAN_LGYPSY,				//77
	MAN_GYPSY,				//78
	MAN_LWAGONFOLK,				//79
	MAN_WAGONFOLK,				//80
	MAN_LTRIBESMAN,				//81
	MAN_TRIBESMAN,				//82
	MAN_LHEADHUNTER,			//83
	MAN_HEADHUNTER,				//84
	MAN_LWOODSMAN,				//85
	MAN_WOODSMAN,				//86
	MAN_LAMAZON,				//87
	MAN_AMAZON,				//88
	MAN_LHILLMAN,				//89
	MAN_HILLMAN,				//90
	MAN_LHALFORC,				//91
	MAN_HALFORC,				//92
	MAN_LCAVEDWELLER,			//93
	MAN_CAVEDWELLER,			//94
	MAN_LTROGLODYTE,			//95
	MAN_TROGLODYTE,				//96
	MAN_LDEEPFFOLK,				//97
	MAN_DEEPFFOLK,				//98
	MAN_LNIGHTSTALKER,			//99
	MAN_NIGHTSTALKER,			//100
	MAN_LCOMMONMAN,				//101
	MAN_COMMONMAN,				//102
	MAN_LGNOLL,				//103
	MAN_GNOLL,				//104
	MAN_LHILLDWARF,				//105
	MAN_HILLDWARF,				//106
	MAN_LMOUNTAINDWARF,			//107
	MAN_MOUNTAINDWARF,			//108
	MAN_LICEDWARF,				//109
	MAN_ICEDWARF,				//110
	MAN_LDESERTDWARF,			//111
	MAN_DESERTDWARF,			//112
	MAN_LUNDERDWARF,			//113
	MAN_UNDERDWARF,				//114
	MAN_LDARKDWARF,				//115
	MAN_DARKDWARF,				//116
	MAN_LDEEPDWARF,				//117
	MAN_DEEPDWARF,				//118
	MAN_LGULLYDWARF,			//119
	MAN_GULLYDWARF,				//120
	MAN_LWOODELF,				//121
	MAN_WOODELF,				//122
	MAN_LSEAELF,				//123
	MAN_SEAELF,				//124
	MAN_LHIGHELF,				//125
	MAN_HIGHELF,				//126
	MAN_LTRIBALELF,				//127
	MAN_TRIBALELF,				//128
	MAN_LNIGHTELF,				//129
	MAN_NIGHTELF,				//130
	MAN_LDRAGONLORD,			//131
	MAN_DRAGONLORD,				//132
	MAN_LDARKELF,				//133
	MAN_DARKELF,				//134
	MAN_LDEATHWALKER,			//135
	MAN_DEATHWALKER,			//136
	MAN_LORC,				//137
	MAN_ORC,				//138
	MAN_LURUK,				//139
	MAN_URUK,				//140
	MAN_LGOBLINMAN,				//141
	MAN_GOBLINMAN,				//142
	MAN_LOGREMAN,				//143
	MAN_OGREMAN,				//144
	MAN_LHOBBIT,				//145
	MAN_HOBBIT,				//146
	MAN_LGNOME,				//147
	MAN_GNOME,				//148
	MAN_LMINOTAUR,				//149
	MAN_MINOTAUR,				//150
	MAN_LLIZARDMAN,				//151
	MAN_LIZARDMAN,				//152
	MAN_LFAIRY,				//153
	MAN_FAIRY,				//154
	MAN_LTITAN,				//155
	MAN_TITAN,				//156
	MAN_HHIGHMAN,				//157
	MAN_HDARKMAN,				//158
	MAN_HHIGHLANDER,			//159
	MAN_HBARBARIAN,				//160
	MAN_HPLAINSMAN,				//161
	MAN_HHELOT,				//162
	MAN_HBEARTRIBE,				//163
	MAN_HNORTHMAN,				//164
	MAN_HGYPSY,				//165
	MAN_HWAGONFOLK,				//166
	MAN_HTRIBESMAN,				//167
	MAN_HHEADHUNTER,			//168
	MAN_HWOODSMAN,				//169
	MAN_HAMAZON,				//170
	MAN_HHILLMAN,				//171
	MAN_HHALFORC,				//172
	MAN_HCAVEDWELLER,			//173
	MAN_HTROGLODYTE,			//174
	MAN_HDEEPFFOLK,				//175
	MAN_HNIGHTSTALKER,			//176
	MAN_HCOMMONMAN,				//177
	MAN_HGNOLL,				//178
	MAN_HHILLDWARF,				//179
	MAN_HMOUNTAINDWARF,			//180
	MAN_HUNDERDWARF,			//181
	MAN_HDARKDWARF,				//182
	MAN_HDEEPDWARF,				//183
	MAN_HGULLYDWARF,			//184
	MAN_HWOODELF,				//185
	MAN_HSEAELF,				//186
	MAN_HHIGHELF,				//187
	MAN_HTRIBALELF,				//188
	MAN_HNIGHTELF,				//189
	MAN_HDRAGONLORD,			//190
	MAN_HDARKELF,				//191
	MAN_HDEATHWALKER,			//192
	MAN_HORC,				//193
	MAN_HURUK,				//194
	MAN_HGOBLINMAN,				//195
	MAN_HOGREMAN,				//196
	MAN_HHOBBIT,				//197
	MAN_HGNOME,				//198
	MAN_HMINOTAUR,				//199
	MAN_HLIZARDMAN,				//200
	MAN_LHORSEMAN,				//201
	MAN_HORSEMAN,				//202
	MAN_HHORSEMAN,				//203
	MAN_LEASTERLING,			//204
	MAN_EASTERLING,				//205
	MAN_HEASTERLING,			//206
	NUMMAN
};

//
// Types of monsters
//
enum {
  MONSTER_NONE,
  MONSTER_WARG,
  MONSTER_WHOR,
  MONSTER_WLIZ,
  MONSTER_HARY,
  MONSTER_GCEN,
  MONSTER_CHIM,
  MONSTER_WMAM,
  MONSTER_FLIZ,
  MONSTER_HUND,
  MONSTER_CHAR,
  MONSTER_BLIZ,
  MONSTER_UNIC,
  MONSTER_DRAK,
  MONSTER_GRIF,
  MONSTER_WELE,
  MONSTER_FDRA,
  MONSTER_ILLUSION,
  MONSTER_EAGLES,
  MONSTER_STEELDRAGON,
  MONSTER_COPPERDRAGON,
  MONSTER_BRONZEDRAGON,
  MONSTER_SILVERDRAGON,
  MONSTER_GOLDENDRAGON,
  MONSTER_ZOMBIE,
  MONSTER_RAT,
  MONSTER_THIEF,
  MONSTER_ANIMATEDTREE,
  MONSTER_WILLOWWISP,
  MONSTER_CARNIVOROUSPLANT,
  MONSTER_KILLERLION,
  MONSTER_CROW,
  MONSTER_SNAKE,
  MONSTER_WILDBOAR,
  MONSTER_WOLF,
  MONSTER_FANGEDLIZARD,
  MONSTER_POISONSPIDER,
  MONSTER_CRAWLER,
  MONSTER_EVILWARRIOR,
  MONSTER_HIGHWAYMAN,
  MONSTER_ROBBER,
  MONSTER_WOLVES,
  MONSTER_CROWS,
  MONSTER_MOUNTAINLIONS,
  MONSTER_GIANTRATS,
  MONSTER_SNAKES,
  MONSTER_LIONS,
  MONSTER_ICEWOLVES,
  MONSTER_POISONSPIDERS,
  MONSTER_FANGEDLIZARDS,
  MONSTER_CRAWLERS,
  MONSTER_LIVINGTREES,
  MONSTER_GRIZZLYBEARS,
  MONSTER_ROCS,
  MONSTER_SWAMPCREATURES,
  MONSTER_TIGERS,
  MONSTER_GIANTSCORPIONS,
  MONSTER_POLARBEARS,
  MONSTER_GIANTSQUID,
  MONSTER_BUGBEARS,
  MONSTER_MAULER,
  MONSTER_TUNNELWORM,
  MONSTER_GREENDRAGON,
  MONSTER_BROWNDRAGON,
  MONSTER_BLUEDRAGON,
  MONSTER_REDDRAGON,
  MONSTER_WHITEDRAGON,
  MONSTER_BLACKDRAGON,
  MONSTER_BOGTHING,
  MONSTER_HYDRA,
  MONSTER_SPHINX,
  MONSTER_KRAKEN,
  MONSTER_ILLYRTHIL,
  MONSTER_GOBLINS,
  MONSTER_SKELETONS,
  MONSTER_IMPS,
  MONSTER_PIRATES,
  MONSTER_MERFOLK,
  MONSTER_MUTANTS,
  MONSTER_CENTAURS,
  MONSTER_KOBOLDS,
  MONSTER_WILDMEN,
  MONSTER_SANDLINGS,
  MONSTER_DROWWARRIORS,
  MONSTER_EVILWARRIORS,
  MONSTER_OGRES,
  MONSTER_YETIS,
  MONSTER_TROLLS,
  MONSTER_ETTINS,
  MONSTER_UNDEAD,
  MONSTER_DEMONS,
  MONSTER_BALROG,
  MONSTER_LICH,
  MONSTER_STORMGIANT,
  MONSTER_CLOUDGIANT,
  MONSTER_EVILSORCERERS,
  MONSTER_EVILMAGICIANS,
  MONSTER_DARKPRIEST,
  MONSTER_STEELDRAGON_S,
  MONSTER_COPPERDRAGON_S,
  MONSTER_BRONZEDRAGON_S,
  MONSTER_SILVERDRAGON_S,
  MONSTER_GOLDENDRAGON_S,
  MONSTER_STEELDRAGON_O,
  MONSTER_COPPERDRAGON_O,
  MONSTER_BRONZEDRAGON_O,
  MONSTER_SILVERDRAGON_O,
  MONSTER_GOLDENDRAGON_O,
  MONSTER_STEELDRAGON_A,
  MONSTER_COPPERDRAGON_A,
  MONSTER_BRONZEDRAGON_A,
  MONSTER_SILVERDRAGON_A,
  MONSTER_GOLDENDRAGON_A,
  MONSTER_STEELDRAGON_B,
  MONSTER_COPPERDRAGON_B,
  MONSTER_BRONZEDRAGON_B,
  MONSTER_SILVERDRAGON_B,
  MONSTER_GOLDENDRAGON_B,
  MONSTER_GREENDRAGON_S,
  MONSTER_BROWNDRAGON_S,
  MONSTER_BLUEDRAGON_S,
  MONSTER_REDDRAGON_S,
  MONSTER_WHITEDRAGON_S,
  MONSTER_BLACKDRAGON_S,
  MONSTER_GREENDRAGON_O,
  MONSTER_BROWNDRAGON_O,
  MONSTER_BLUEDRAGON_O,
  MONSTER_REDDRAGON_O,
  MONSTER_WHITEDRAGON_O,
  MONSTER_BLACKDRAGON_O,
  MONSTER_GREENDRAGON_A,
  MONSTER_BROWNDRAGON_A,
  MONSTER_BLUEDRAGON_A,
  MONSTER_REDDRAGON_A,
  MONSTER_WHITEDRAGON_A,
  MONSTER_BLACKDRAGON_A,
  MONSTER_GREENDRAGON_B,
  MONSTER_BROWNDRAGON_B,
  MONSTER_BLUEDRAGON_B,
  MONSTER_REDDRAGON_B,
  MONSTER_WHITEDRAGON_B,
  MONSTER_BLACKDRAGON_B,
  MONSTER_DDRA,
  MONSTER_SDRA,
  MONSTER_CDRA,
  MONSTER_RDRA,
  NUMMONSTERS
};

//
// Types of weapons
//
// GGO
// Completely redisigned table
//
enum {
	WEAPON_NONE,
	WEAPON_RAINBOWDAGGER,
	WEAPON_DARKSWORD,
	WEAPON_STARAXE,	
	WEAPON_RUNESWORD,
	WEAPON_FLAMINGSWORD,
	WEAPON_LONGBOW,
	WEAPON_HEAVYCROSSBOW,
	WEAPON_CROSSBOW,
	WEAPON_BOW,
	WEAPON_ENCHANTEDSHORTBOW,
	WEAPON_ENCHANTEDLIGHTCROSSBOW,
	WEAPON_SHORTBOW,
	WEAPON_LIGHTCROSSBOW,
	WEAPON_ENCHANTEDJAVELIN,
	WEAPON_JAVELIN,
	WEAPON_MAGESTAFF,
	WEAPON_SWIFTAXE,
	WEAPON_ICESPEAR,
	WEAPON_FIRESPEAR,
	WEAPON_ADLONGSWORD,
	WEAPON_FOIL,
	WEAPON_WARHAMMER,
	WEAPON_WARMACE,
	WEAPON_ADBROADSWORD,
	WEAPON_BARDICHE,
	WEAPON_WARAXE,
	WEAPON_ADSWORD,
	WEAPON_WARLANCE,
	WEAPON_WARSPEAR,
	WEAPON_WARSTAFF,
	WEAPON_EVENINGSTAR,
	WEAPON_MILONGSWORD,
	WEAPON_EPEE,
	WEAPON_SKULLCRUSHER,
	WEAPON_MIBROADSWORD,
	WEAPON_BATTLEMACE,
	WEAPON_ENCHANTEDLONGSWORD,
	WEAPON_CLEAVER,
	WEAPON_HALBERD,
	WEAPON_ADDAGGER,
	WEAPON_ENCHANTEDSABRE,
	WEAPON_MISWORD,
	WEAPON_ENCHANTEDBATTLEHAMMER,
	WEAPON_ENCHANTEDBROADSWORD,
	WEAPON_ENCHANTEDMACE,
	WEAPON_BATTLELANCE,
	WEAPON_BATTLESPEAR,
	WEAPON_TRISTAR,
	WEAPON_ENCHANTEDBATTLEAXE,
	WEAPON_ENCHANTEDPIKE,
	WEAPON_BATTLESTAFF,
	WEAPON_ENCHANTEDSWORD,
	WEAPON_ENCHANTEDLANCE,
	WEAPON_ENCHANTEDSPEAR,
	WEAPON_ENCHANTEDMORNINGSTAR,
	WEAPON_ENCHANTEDQUARTERSTAFF,
	WEAPON_MIDAGGER,
	WEAPON_ENCHANTEDDAGGER,
	WEAPON_ENCHANTEDKNIFE,
	WEAPON_LONGSWORD,
	WEAPON_ENCHANTEDCLUB,
	WEAPON_ENCHANTEDHAMMER,
	WEAPON_ENCHANTEDAXE,
	WEAPON_ENCHANTEDPICK,
	WEAPON_ENCHANTEDPARRYINGDAGGER,
	WEAPON_SABRE,
	WEAPON_BATTLEHAMMER,
	WEAPON_BROADSWORD,
	WEAPON_MACE,
	WEAPON_ENRUNEDAXE,
	WEAPON_BATTLEAXE,
	WEAPON_PIKE,
	WEAPON_SWORD,
	WEAPON_LANCE,
	WEAPON_ENRUNEDSPEAR,
	WEAPON_SPEAR,
	WEAPON_MORNINGSTAR,
	WEAPON_QUARTERSTAFF,
	WEAPON_HAMMER,
	WEAPON_AXE,
	WEAPON_PICK,
	WEAPON_DAGGER,
	WEAPON_CLUB,
	WEAPON_PDAGGER,
	WEAPON_KNIFE,
	WEAPON_LASSO,
	WEAPON_NET,
	NUMWEAPONS
};

//
// Types of armor
//
// GGO
// Completely redisigned table
//
enum {
	ARMOR_NONE,
	ARMOR_CLOAKOFI,
	ARMOR_DRAGONSCALESARMOR,
	ARMOR_ADMANTIUMPLATEARMOR,
	ARMOR_ADMANTIUMSCALEARMOR,
	ARMOR_ADMANTIUMCHAINARMOR,
	ARMOR_MITHRILPLATEARMOR,
	ARMOR_MITHRILSCALEARMOR,
	ARMOR_MITHRILCHAINARMOR,
	ARMOR_ENCHANTEDPLATEARMOR,
	ARMOR_ENCHANTEDSCALEARMOR,
	ARMOR_ENCHANTEDCHAINARMOR,
	ARMOR_IRONPLATEARMOR,
	ARMOR_IRONSCALEARMOR,
	ARMOR_IRONCHAINARMOR,
	ARMOR_BPLATE,
	ARMOR_ENCHANTEDLEATHERARMOR,
	ARMOR_ENCHANTEDCLOTHARMOR,
	ARMOR_LEATHERARMOR,
	ARMOR_CLOTHARMOR,
	ARMOR_SHIELD,
	ARMOR_ASHIELD,
	ARMOR_MSHIELD,
	ARMOR_ISHIELD,
	ARMOR_WSHIELD,
	NUMARMORS
};

//
// Types of mounts
//
enum {
	MOUNT_NONE,
	MOUNT_MFLI,
	MOUNT_WING,
	MOUNT_MBAT,
	MOUNT_MEAG,
	MOUNT_MOLE,
	MOUNT_ELEP,
	MOUNT_MAMM,
	MOUNT_HORS,
	MOUNT_MLIZ,
	MOUNT_CAME,
	MOUNT_MSPI,
	MOUNT_MWOL,
	MOUNT_PONY,
	NUMMOUNTS
};

//
// Other battle items
//
enum {
	BATTLE_NONE,
	BATTLE_RUNESWORD,
	BATTLE_STAFFOFL,
	BATTLE_STAFFOFF,
	BATTLE_FLAMINGSWORD,
	BATTLE_AOFI,
	BATTLE_AMULETOFP,
	BATTLE_SHIELDSTONE,
	BATTLE_MAGESTAFF,
	NUMBATTLEITEMS
};

//
// Types of skills.
//
enum {
	S_MINING,				//0
	S_LUMBERJACK,				//1
	S_QUARRYING,				//2
	S_HUNTING,				//3
	S_FISHING,				//4
	S_HERBLORE,				//5
	S_SMITHING,				//6
	S_TOOLMAKING,				//7
	S_BUILDING,				//8
	S_SHIPBUILDING,				//9
	S_ENTERTAINMENT,			//10
	S_TACTICS,				//11
	S_COMBAT,				//12
	S_RIDING,				//13
	S_CROSSBOW,				//14
	S_ARCHERY,				//15
	S_STEALTH,				//16
	S_OBSERVATION,				//17
	S_HEALING,				//18
	S_SAILING,				//19
	S_FARMING,				//20
	S_RANCHING,				//21
	S_WEAPONCRAFT,				//22
	S_ARMORCRAFT,				//23
	S_GEMCUTTING,				//24
	S_ANIMALTRAINING,			//25
	S_ANIMALTAMING,				//26
	S_MONSTERTAMING,			//27
	S_COOKING,				//28
	S_MANIPULATE,				//29
	S_FORCE,				//30
	S_PATTERN,				//
	S_SPIRIT,				//
	S_FIRE,					//
	S_ICE,					//
	S_MIND,					//
	S_EARTHQUAKE,				//
	S_FORCE_SHIELD,				//
	S_ENERGY_SHIELD,			//
	S_WEATHER_SHIELD,			//
	S_SPIRIT_SHIELD,			//
	S_MAGICAL_HEALING,			//
	S_GATE_LORE,				//
	S_FARSIGHT,				//
	S_TELEPORTATION,			//
	S_PORTAL_LORE,				//
	S_MIND_READING,				//
	S_WEATHER_LORE,				//
	S_SUMMON_WIND,				//
	S_SUMMON_STORM,				//
	S_SUMMON_TORNADO,			//
	S_CALL_LIGHTNING,			//
	S_CLEAR_SKIES,				//
	S_EARTH_LORE,				//
	S_WOLF_LORE,				//
	S_BIRD_LORE,				//
	S_DRAGON_LORE,				//
	S_WYRM_LORE,				//
	S_SUMMON_DRAGON,			//
	S_SUMMON_WYRM,				//
	S_NECROMANCY,				//
	S_SUMMON_SKELETONS,			//
	S_RAISE_UNDEAD,				//
	S_SUMMON_LICH,				//
	S_CREATE_AURA_OF_FEAR,			//
	S_SUMMON_BLACK_WIND,			//
	S_ENERGY_BLAST,				//
	S_BANISH_UNDEAD,			//
	S_DEMON_LORE,				//
	S_SUMMON_IMPS,				//
	S_SUMMON_DEMON,				//
	S_SUMMON_BALROG,			//
	S_BANISH_DEMONS,			//
	S_ILLUSION,				//
	S_PHANTASMAL_ENTERTAINMENT,		//
	S_CREATE_PHANTASMAL_BEASTS,		//
	S_CREATE_PHANTASMAL_UNDEAD,		//
	S_CREATE_PHANTASMAL_DEMONS,		//
	S_INVISIBILITY,				//
	S_TRUE_SEEING,				//
	S_DISPEL_ILLUSIONS,			//
	S_ARTIFACT_LORE,			//
	S_CREATE_RING_OF_INVISIBILITY,		//
	S_CREATE_CLOAK_OF_INVULNERABILITY,	//
	S_CREATE_STAFF_OF_FIRE,			//
	S_CREATE_STAFF_OF_LIGHTNING,		//
	S_CREATE_AMULET_OF_TRUE_SEEING,		//
	S_CREATE_AMULET_OF_PROTECTION,		//
	S_CREATE_RUNESWORD,			//
	S_CREATE_FLAMING_SWORD,			//
	S_CREATE_SHIELDSTONE,			//
	S_CREATE_MAGIC_CARPET,			//
	S_ENGRAVE_RUNES_OF_WARDING,		//
	S_CONSTRUCT_GATE,			//
	S_ENCHANT_WEAPONS,			//
	S_ENCHANT_ARMOR,			//
	S_CONSTRUCT_PORTAL,			//
	S_CREATE_FOOD,				//
	NSKILLS			
};

//
// Types of special attacks
//
enum {
	SPECIAL_NONE_DUMMY,
	SPECIAL_FIREBALL,
	SPECIAL_ICECONE,
	SPECIAL_MINDSTRIKE,
	SPECIAL_HELLFIRE,
	SPECIAL_CAUSEFEAR,
	SPECIAL_LSTRIKE,
	SPECIAL_MINDBLAST,
	SPECIAL_EARTHQUAKE,
	SPECIAL_TRAMPLING,
	SPECIAL_FORCE_SHIELD,
	SPECIAL_ENERGY_SHIELD,
	SPECIAL_WEATHER_SHIELD,
	SPECIAL_SPIRIT_SHIELD,
	SPECIAL_DISPEL_ILLUSIONS,
	SPECIAL_SUMMON_STORM,
	SPECIAL_TORNADO,
	SPECIAL_CLEAR_SKIES,
	SPECIAL_BLACK_WIND,
	SPECIAL_ENERGY_BLAST,
	SPECIAL_BANISH_UNDEAD,
	SPECIAL_BANISH_DEMONS,
	SPECIAL_FIREBREATH,
	SPECIAL_POISONBREATH,
	SPECIAL_ICEBREATH,
	SPECIAL_CAMEL_FEAR,
	SPECIAL_INVULNERABILITY,
	SPECIAL_MAGESTAFF,
	SPECIAL_RAINBOW,
	NUMSPECIALS
};

//
// Types of objects.
//
enum {
	O_DUMMY,
	O_ROWINGBOAT,
	O_LONGBOAT,
	O_CLIPPER,
	O_GALLEON,
	O_AGALLEON,
	O_WGALLEON,
	O_AIRSHIP,
	O_HERMITSHUT,
	O_TOWER,
	O_GRANDTOWER,
	O_STOCKADE,
	O_GRANDSTOCKADE,
	O_FORT,
	O_GRANDFORT,
	O_CASTLE,
	O_GRANDCASTLE,
	O_CITADEL,
	O_GRANDCITADEL,
	O_FORTRESS,
	O_GRANDFORTRESS,
	O_MAGICALTOWER,
	O_MAGICALCASTLE,
	O_MAGICALFORTRESS,
	O_PALACE,
	O_CPALACE,
	O_CLOUDPALACE,
	O_HTOWER,
	O_HPTOWER,
	O_NGUILD,
	O_AGUILD,
	O_GDCLIFFS,
	O_EDCLIFFS,
	O_SHAFT,
	O_GREENLAIR,
	O_BROWNLAIR,
	O_BLUELAIR,
	O_REDLAIR,
	O_WHITELAIR,
	O_BLACKLAIR,
	O_RUIN,
	O_CAVE,
	O_DEMONPIT,
	O_CRYPT,
	O_ISLE,
	O_DERELICT,
	O_PEATBOG,
	O_WHIRL,
	O_MAGETOWER,
	O_DARKTOWER,
	O_GIANTCASTLE,
	O_ILAIR,
	O_ICECAVE,
	O_THICKET,
	O_PYRAMID,
	O_BKEEP,
	O_ATEMPLE,
	O_TEMPLE,
	O_HUT,
	O_HOUSE,
	O_AQUEDUCT,
	O_INN,
	O_FAIR,
	O_FARM,
	O_MILL,
	O_MUSHROOMFARM,
	O_IRRIGATION,
	O_VINEYARD,
	O_WINEPRESS,
	O_COTTONPLANTATION,
	O_COTTONCOLLECTORS,
	O_TRUFFLESPLANTATION,
	O_BOARPEN,
	O_TOBACCOPLANTATION,
	O_HORTICULTURE,
	O_SHEEPFARM,
	O_SHEEPDIP,
	O_WOOLINGERFARM,
	O_WOOLINGERDIP,
	O_RANCH,
	O_SLAUGHTERHOUSE,
	O_LIZARDRANCH,
	O_LIZARDSLAUGHTERHOUSE,
	O_SHEPHERDHUT,
	O_MENAGERIE,
	O_FISHINGFLEET,
	O_JETTY,
	O_ARTIFICIALREEF,
	O_DIVINGFLOATS,
	O_WHALINGFLEET,
	O_MINE,
	O_FURNACE,
	O_GEMMINE,
	O_GEMAPPRAISER,
	O_MITHRILMINE,
	O_PROSPECTORSHUT,
	O_ADMANTIUMMINE,
	O_GOLDMINE,
	O_TREENURSERY,
	O_TIMBERYARD,
	O_TREETENDERSHUT,
	O_SAWINGMILL,
	O_YEWGROVE,
	O_QUARRY,
	O_STONECUTTERSHUT,
	O_ROOTSTONEQUARRY,
	O_STONEMASONSHUT,
	O_CORESTONEQUARRY,
	O_HUNTINGHUT,
	O_HUNTINGSTAND,
	O_TRAPPINGHUT,
	O_CAGETRAP,
	O_WALKWAY,
	O_GASTANK,
	O_TRAPPINGLODGE,
	O_HERBGARDEN,
	O_HERBALISTSTORE,
	O_FUNGUSGARDEN,
	O_DRYINGSHED,
	O_DRUIDCIRCLE,
	O_PONYSTABLE,
	O_WOLFPEN,
	O_SPIDERSTABLE,
	O_STABLE,
	O_CAMELSTABLE,
	O_LIZARDSTABLE,
	O_EYRIE,
	O_BATCAVE,
	O_ELEPHANTSTABLE,
	O_MAMMOTHSTABLE,
	O_MOLEBURROW,
	O_WINGEDHORSESTABLE,
	O_FLYINGLIZARDSTABLE,
	O_WARGPIT,
	O_TOURNAMENTCOURSE,
	O_TRAININGPIT,
	O_HARPYNEST,
	O_BREEDINGPIT,
	O_CHIMERAROOST,
	O_MAMMOTHWARSCHOOL,
	O_VOLCANICPOOL,
	O_KENNEL,
	O_TOURNAMENTPARCOURS,
	O_TRAININGPEN,
	O_VIRGINARY,
	O_DRAKENSTEIN,
	O_GRIFFONSTABLE,
	O_ELEPHANTWARSCHOOL,
	O_FIREDRAKECLIFF,
	O_TAVERN,
	O_JOINER,
	O_SMITHY,
	O_WEAPONFORGE,
	O_ARMORFORGE,
	O_TEAMTRAINER,
	O_APOTHECARY,
	O_PELTMONGER,
	O_SCULPTOR,
	O_JEWELER,
	O_FISHERY,
	O_FARMHOUSE,
	O_RANCHHOUSE,
	O_CHANDLER,
	O_RUNEMASTER,
	O_ROADN,
	O_ROADNW,
	O_ROADNE,
	O_ROADSW,
	O_ROADSE,
	O_ROADS,
	NOBJECTS
};

//
// Types of terrain
//
/* ARegion Types */
enum {
	R_OCEAN,
	R_PLAIN,
	R_FOREST,
	R_MOUNTAIN,
	R_SWAMP,
	R_JUNGLE,
	R_DESERT,
	R_TUNDRA,
	R_CAVERN,
	R_UFOREST,
	R_TUNNELS,
	R_NEXUS,
	R_VOLCANO,
	R_LAKE,
	R_ISLAND_PLAIN,
	R_ISLAND_SWAMP,
	R_ISLAND_MOUNTAIN,
	R_T_OCEAN1,
	R_T_PLAIN1,
	R_T_PLAIN2,
	R_T_PLAIN3,
	R_T_LAKE1,
	R_T_LAKE2,
	R_T_LAKE3,
	R_T_FOREST1,
	R_T_FOREST2,
	R_T_FOREST3,
	R_T_MYSTFOREST1,
	R_T_MOUNTAIN1,
	R_T_MOUNTAIN2,
	R_T_MOUNTAIN3,
	R_T_HILL1,
	R_T_HILL2,
	R_T_HILL3,
	R_T_SWAMP1,
	R_T_SWAMP2,
	R_T_SWAMP3,
	R_T_JUNGLE1,
	R_T_JUNGLE2,
	R_T_JUNGLE3,
	R_T_DESERT1,
	R_T_DESERT2,
	R_T_DESERT3,
	R_T_VOLCANO1,
	R_T_TUNDRA1,
	R_T_TUNDRA2,
	R_T_TUNDRA3,
	R_T_CAVERN1,
	R_T_CAVERN2,
	R_T_CAVERN3,
	R_T_UNDERFOREST1,
	R_T_UNDERFOREST2,
	R_T_UNDERFOREST3,
	R_T_TUNNELS1,
	R_T_TUNNELS2,
	R_T_TUNNELS3,
	R_T_GROTTO1,
	R_T_PLAIN4,
	R_T_PLAIN5,
	R_T_PLAIN6,
	R_T_LAKE4,
	R_T_LAKE5,
	R_T_LAKE6,
	R_T_FOREST4,
	R_T_FOREST5,
	R_T_FOREST6,
	R_T_MYSTFOREST2,
	R_T_MOUNTAIN4,
	R_T_MOUNTAIN5,
	R_T_MOUNTAIN6,
	R_T_HILL4,
	R_T_HILL5,
	R_T_HILL6,
	R_T_SWAMP4,
	R_T_SWAMP5,
	R_T_SWAMP6,
	R_T_JUNGLE4,
	R_T_JUNGLE5,
	R_T_JUNGLE6,
	R_T_DESERT4,
	R_T_DESERT5,
	R_T_DESERT6,
	R_T_VOLCANO2,
	R_T_TUNDRA4,
	R_T_TUNDRA5,
	R_T_TUNDRA6,
	R_T_CAVERN4,
	R_T_CAVERN5,
	R_T_CAVERN6,
	R_T_DEEPFOREST1,
	R_T_DEEPFOREST2,
	R_T_DEEPFOREST3,
	R_T_TUNNELS4,
	R_T_TUNNELS5,
	R_T_TUNNELS6,
	R_T_GROTTO2,
	R_CE_OCEAN,
	R_CE_OCEAN1,
	R_CE_GDPLAIN,
	R_CE_GDPLAIN1,
	R_CE_EVPLAIN,
	R_CE_EVPLAIN1,
	R_CE_GDGRASSLAND,
	R_CE_GDGRASSLAND1,
	R_CE_EVGRASSLAND,
	R_CE_EVGRASSLAND1,
	R_CE_GDLAKE,
	R_CE_NELAKE,
	R_CE_EVLAKE,
	R_CE_GDFOREST,
	R_CE_GDFOREST1,
	R_CE_EVFOREST,
	R_CE_EVFOREST1,
	R_CE_MYSTFOREST,
	R_CE_MYSTFOREST1,
	R_CE_GDMOUNTAIN,
	R_CE_GDMOUNTAIN1,
	R_CE_EVMOUNTAIN,
	R_CE_EVMOUNTAIN1,
	R_CE_GDHILL,
	R_CE_GDHILL1,
	R_CE_EVHILL,
	R_CE_EVHILL1,
	R_CE_GDSWAMP,
	R_CE_GDSWAMP1,
	R_CE_EVSWAMP,
	R_CE_EVSWAMP1,
	R_CE_GDJUNGLE,
	R_CE_GDJUNGLE1,
	R_CE_EVJUNGLE,
	R_CE_EVJUNGLE1,
	R_CE_GDDESERT,
	R_CE_GDDESERT1,
	R_CE_EVDESERT,
	R_CE_EVDESERT1,
	R_CE_WASTELAND,
	R_CE_WASTELAND1,
	R_CE_GDTUNDRA,
	R_CE_GDTUNDRA1,
	R_CE_EVTUNDRA,
	R_CE_EVTUNDRA1,
	R_CE_GDCAVERN,
	R_CE_GDCAVERN1,
	R_CE_EVCAVERN,
	R_CE_EVCAVERN1,
	R_CE_GDUFOREST,
	R_CE_GDUFOREST1,
	R_CE_EVUFOREST,
	R_CE_EVUFOREST1,
	R_CE_TUNNELS,
	R_CE_TUNNELS1,
	R_CE_GDULAKE,
	R_CE_NEULAKE,
	R_CE_EVULAKE,
	R_CE_GDDCAVERN,
	R_CE_GDDCAVERN1,
	R_CE_EVDCAVERN,
	R_CE_EVDCAVERN1,
	R_CE_GDDFOREST,
	R_CE_GDDFOREST1,
	R_CE_EVDFOREST,
	R_CE_EVDFOREST1,
	R_CE_DTUNNELS,
	R_CE_DTUNNELS1,
	R_T_MINES1,
	R_T_MINES2,
	R_T_MINES3,
	R_T_MINES4,
	R_T_MINES5,
	R_T_MINES6,
	R_T_CHAMBER1,
	R_T_CHAMBER2,
	R_T_CHAMBER3,
	R_T_CHAMBER4,
	R_T_CHAMBER5,
	R_T_CHAMBER6,
	R_CE_ICE,
	R_CE_GLACIER,
	R_CE_CRYSTALCAVERN,
	R_CE_BLUECAVERN,
	R_CE_REDCAVERN,
	R_CE_YELLOWCAVERN,
	R_CE_ORANGECAVERN,
	R_CE_GREENCAVERN,
	R_CE_VIOLETCAVERN,
	R_CE_BLACKCAVERN,
	R_CE_WHITECAVERN,
	R_NUM
};

// Types of effects
enum {
	EFFECT_DAZZLE,
	EFFECT_FEAR,
	EFFECT_STORM,
	NUMEFFECTS
};

// Types of ranges
enum {
	RANGE_TELEPORT,
	RANGE_PORTAL_LORE,
	RANGE_FARSIGHT,
	RANGE_WEATHER_LORE,
	RANGE_CLEAR_SKIES,
	NUMRANGES
};

enum {
  SUMMON_BALROG,
  SUMMON_DEMON,
  SUMMON_IMP,
  SUMMON_LICH,
  SUMMON_UNDEAD,
  SUMMON_SKELETON,
  SUMMON_WOLF,
  SUMMON_BIRD,
  SUMMON_DRAGON,
};

#endif
