// START A3HEADER
//
// This source file is part of the Atlantis PBM game program.
// Copyright (C) 1995-1999 Geoff Dunbar
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation; either version 2
// of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program, in the file license.txt. If not, write
// to the Free Software Foundation, Inc., 59 Temple Place - Suite 330,
// Boston, MA 02111-1307, USA.
//
// See the Atlantis Project web page for details:
// http://www.prankster.com/project
//
// END A3HEADER
//
#ifndef RULES_H
#define RULES_H

//
// The items
//
enum {
	I_LEADERS,				//0
	I_MAN,					//1
	//
	I_TLHUMAN,				//2
	I_TRHUMAN,				//3
	I_TLVIKING,				//4
	I_TRVIKING,				//5
	I_TLDERVISH,				//6
	I_TRNOMAD,				//7
	I_TLBARBARIAN,				//8
	I_TRBARBARIAN,				//9
	I_TLHIGHLANDER,				//10
	I_TRCLANSMAN,				//11
	I_TLIMPERIAL,				//12
	I_TRIMPERIAL,				//13
	I_TLTRIBESMAN,				//14
	I_TRTRIBESMAN,				//15
	I_TLFFOLK,				//16
	I_TRFFOLK,				//17
	I_TLCAJUN,				//18
	I_TRLIZARDMAN,				//19
	I_TLLOWLANDER,				//20
	I_TRHALFING,				//21
	I_TLELF,				//22
	I_TRHALFELF,				//23
	I_TLDARKMAN,				//24
	I_TRDARKMAN,				//25
	I_TLGNOME,				//26
	I_TRGNOME,				//27
	I_TLDWARF,				//28
	I_TRDWARF,				//29
	I_TLHOBGOBLIN,				//30
	I_TRGOBLIN,				//31
	I_TLBUCCANEER,				//32
	I_TRBUCCANEER,				//33
	I_TLSANDLING,				//34
	I_TRSANDLING,				//35
	I_TLTROLL,				//36
	I_TRGNOLL,				//37
	I_TLURUK,				//38
	I_TRORC,				//39
	I_TLBLACKKEEP,				//40
	I_TRBLACKKEEP,				//41
	I_TLHEADHUNTER,				//42
	I_TRHEADHUNTER,				//43
	I_TLOGRE,				//44
	I_TROGRE,				//45
	I_TLSERPENTPEOPLE,			//46
	I_TRSERPENTPEOPLE,			//47
	I_TLREPUBLICAN,				//48
	I_TRREPUBLICAN,				//49
	I_TLAMAZON,				//50
	I_TRAMAZON,				//51
	I_TLMINOTAUR,				//52
	I_TRMINOTAUR,				//53
	I_TLDROW,				//54
	I_TRDROW,				//55
	I_TLDUERGAR,				//56
	I_TRDUERGAR,				//57
	// 
	I_BONDSMAN,				//58
	I_LBONDSMAN,				//59
	I_SLAVE,				//60
	I_MERCENARY,				//61
	// Ceran: human races
	I_LHIGHMAN,				//62
	I_HIGHMAN,				//63
	I_HHIGHMAN,				//64
	I_LDARKMAN,				//65
	I_DARKMAN,				//66
	I_HDARKMAN,				//67
	I_LHIGHLANDER,				//68
	I_HIGHLANDER,				//69
	I_HHIGHLANDER,				//70
	I_LBARBARIAN,				//71
	I_BARBARIAN,				//72
	I_HBARBARIAN,				//73
	I_LPLAINSMAN,				//74
	I_PLAINSMAN,				//75
	I_HPLAINSMAN,				//76
	I_LHELOT,				//77
	I_HELOT,				//78
	I_HHELOT,				//79
	I_LBEARTRIBE,				//80
	I_BEARTRIBE,				//81
	I_HBEARTRIBE,				//82
	I_LNORTHMAN,				//83
	I_NORTHMAN,				//84
	I_HNORTHMAN,				//85
	I_LGYPSY,				//86
	I_GYPSY,				//87
	I_HGYPSY,				//88
	I_LWAGONFOLK,				//89
	I_WAGONFOLK,				//90
	I_HWAGONFOLK,				//91
	I_LTRIBESMAN,				//92
	I_TRIBESMAN,				//93
	I_HTRIBESMAN,				//94
	I_LHEADHUNTER,				//95
	I_HEADHUNTER,				//96
	I_HHEADHUNTER,				//97
	I_LWOODSMAN,				//98
	I_WOODSMAN,				//99
	I_HWOODSMAN,				//100
	I_LAMAZON,				//101
	I_AMAZON,				//102
	I_HAMAZON,				//103
	I_LHILLMAN,				//104
	I_HILLMAN,				//105
	I_HHILLMAN,				//106
	I_LHALFORC,				//107
	I_HALFORC,				//108
	I_HHALFORC,				//109
	I_LHORSEMAN,				//110
	I_HORSEMAN,				//111
	I_HHORSEMAN,				//112
	I_LEASTERLING,				//113
	I_EASTERLING,				//114
	I_HEASTERLING,				//115
	I_LCAVEDWELLER,				//116
	I_CAVEDWELLER,				//117
	I_HCAVEDWELLER,				//118
	I_LTROGLODYTE,				//119
	I_TROGLODYTE,				//120
	I_HTROGLODYTE,				//121
	I_LDEEPFFOLK,				//122
	I_DEEPFFOLK,				//123
	I_HDEEPFFOLK,				//124
	I_LNIGHTSTALKER,			//125
	I_NIGHTSTALKER,				//126
	I_HNIGHTSTALKER,			//127
	I_LCOMMONMAN,				//128
	I_COMMONMAN,				//129
	I_HCOMMONMAN,				//130
	// Ceran: dwarven races
	I_LHILLDWARF,				//131
	I_HILLDWARF,				//132
	I_HHILLDWARF,				//133
	I_LMOUNTAINDWARF,			//134
	I_MOUNTAINDWARF,			//135
	I_HMOUNTAINDWARF,			//136
	I_LUNDERDWARF,				//137
	I_UNDERDWARF,				//138
	I_HUNDERDWARF,				//139
	I_LDARKDWARF,				//140
	I_DARKDWARF,				//141
	I_HDARKDWARF,				//142
	I_LDEEPDWARF,				//143
	I_DEEPDWARF,				//144
	I_HDEEPDWARF,				//145
	I_LGULLYDWARF,				//146
	I_GULLYDWARF,				//147
	I_HGULLYDWARF,				//148
	// Ceran: elven races
	I_LWOODELF,				//149
	I_WOODELF,				//150
	I_HWOODELF,				//151
	I_LSEAELF,				//152
	I_SEAELF,				//153
	I_HSEAELF,				//154
	I_LHIGHELF,				//155
	I_HIGHELF,				//156
	I_HHIGHELF,				//157
	I_LTRIBALELF,				//158
	I_TRIBALELF,				//159
	I_HTRIBALELF,				//160
	I_LNIGHTELF,				//161
	I_NIGHTELF,				//162
	I_HNIGHTELF,				//163
	I_LDRAGONLORD,				//164
	I_DRAGONLORD,				//165
	I_HDRAGONLORD,				//166
	I_LDARKELF,				//167
	I_DARKELF,				//168
	I_HDARKELF,				//169
	I_LDEATHWALKER,				//170
	I_DEATHWALKER,				//171
	I_HDEATHWALKER,				//172
	I_LHALFELF,				//173
	I_HALFELF,				//174
	I_HHALFELF,				//175
	// Ceran: goblinoid races
	I_LORC,					//176
	I_ORC,					//177
	I_HORC,					//178
	I_LURUK,				//179
	I_URUK,					//180
	I_HURUK,				//181
	I_LGOBLINMAN,				//182
	I_GOBLINMAN,				//183
	I_HGOBLINMAN,				//184
	I_LOGREMAN,				//185
	I_OGREMAN,				//186
	I_HOGREMAN,				//187
	I_LGNOLL,				//188
	I_GNOLL,				//189
	I_HGNOLL,				//190
	// Ceran: other races
	I_LHOBBIT,				//191
	I_HOBBIT,				//192
	I_HHOBBIT,				//193
	I_LGNOME,				//194
	I_GNOME,				//195
	I_HGNOME,				//196
	I_LMINOTAUR,				//197
	I_MINOTAUR,				//198
	I_HMINOTAUR,				//199
	I_LLIZARDMAN,				//200
	I_LIZARDMAN,				//201
	I_HLIZARDMAN,				//202
	I_LFAIRY,				//203
	I_FAIRY,				//204
	I_HFAIRY,				//205
	I_LTITAN,				//206
	I_TITAN,				//207
	I_HTITAN,				//208
	// ressouces
	I_SILVER,				//209

	I_GRAIN,				//210
	I_MUSHROOM,				//211
	I_GRAPES,				//212
	I_COTTON,				//213
	I_TRUFFLES,				//214
	I_TOBACCO,				//215
	I_DYEPLANT,				//216

	I_SHEEP,				//217
	I_WOOLINGER,				//218
	I_LIVESTOCK,				//219
	I_LIZARD,				//220
	I_POINTYEAREDSHEEP,			//221
	I_SPIDER,				//222

	I_FISH,					//223
	I_MUSSELS,				//224
	I_WHALE,				//225

	I_IRON,					//226
	I_ROUGHGEM,				//227
	I_MITHRIL,				//228
	I_ADMANTIUM,				//229
	I_GOLD,					//230

	I_WOOD,					//231
	I_IRONWOOD,				//232
	I_YEW,					//233

	I_STONE,				//234
	I_ROOTSTONE,				//235
	I_CORESTONE,				//236

	I_GAME,					//237
	I_FURREDANIMAL,				//238
	I_MARSHGAS,				//239
	I_PELTANIMAL,				//240

	I_HERB,					//241
	I_FUNGUS,				//242
	I_MEDICINEPLANT,			//243
	// mounts
	I_PONY,					//244
	I_GIANTWOLF,				//245
	I_GIANTSPIDER,				//246
	I_HORSE,				//247
	I_CAMEL,				//248
	I_GIANTLIZARD,				//249
	I_GIANTEAGLE,				//250
	I_GIANTBAT,				//251
	I_ELEPHANT,				//252
	I_MAMMOTH,				//253
	I_GIANTMOLE,				//254
	I_WINGEDHORSE,				//255
	I_FLYINGLIZARD,				//256
	// warmounts for evil races
	I_WARG,					//257
	I_WARHORSE,				//258
	I_WARLIZARD,				//259
	I_HARPY,				//260
	I_GIANTCENTIPEDE,			//261
	I_CHIMERA,				//262
	I_WARMAMMOTH,				//263
	I_FIRELIZARD,				//264
	I_WALKINGFORTRESS,			//265
	// warmounts for good races
	I_HUNTINGDOG,				//266
	I_CHARGER,				//267
	I_BATTLELIZARD,				//268
	I_UNICORN,				//269
	I_DRAKE,				//270
	I_GRIFFON,				//271
	I_WARELEPHANT,				//272
	I_FIREDRAKE,				//273
	I_BEHEMOTH,				//274
	// high level warmounts
	I_DESERTDRAKE,				//275
	I_SWAMPDRAKE,				//276
	I_CAVEDRAKE,				//277
	I_RAINBOWDRAKE,				//278
	// crystals
	I_BLUECRYSTAL,				//279
	I_REDCRYSTAL,				//280
	I_YELLOWCRYSTAL,			//281
	I_ORANGECRYSTAL,			//282
	I_GREENCRYSTAL,				//283
	I_VIOLETCRYSTAL,			//284
	I_WHITECRYSTAL,				//285
	I_BLACKCRYSTAL,				//286
	// improved ressouces
	I_HEARTWOOD,				//287
	I_DWARVINSTEEL,				//288
	I_STEEL,				//289
	// improved crystals
	I_BLUEPOWERCRYSTAL,			//290
	I_REDPOWERCRYSTAL,			//291
	I_YELLOWPOWERCRYSTAL,			//292
	I_ORANGEPOWERCRYSTAL,			//293
	I_GREENPOWERCRYSTAL,			//294
	I_VIOLETPOWERCRYSTAL,			//295
	I_WHITEPOWERCRYSTAL,			//296
	I_BLACKPOWERCRYSTAL,			//297
	// monster spoils
	I_DRAGONSCALES,				//298
	I_DRAGONBLOOD,				//299
	I_SWAMPCRYSTAL,				//300
	I_HYDRABLOOD,				//301
	I_TOME,					//302
	I_RUBY,					//303
	I_KRAKENEYE,				//304
	I_ILLYRTHIDBRAIN,			//305
	I_BEARCLAWS,				//306
	I_ROCFEATHER,				//307
	I_SLIME,				//308
	I_SQUIDBEAK,				//309
	I_ACID,					//310
	I_EGG,					//311
	I_RATTAIL,				//312
	// trade goods
	I_MEAT,					//313
	I_HIDE,					//314
	I_RATION,				//315
	I_FOOD,					//316
	I_DELICATESSEN,				//317
	I_BEER,					//318
	I_WINE,					//319
	I_CLOTHES,				//320
	I_PARFAIT,				//321
	I_CIGARS,				//322
	I_DYE,					//323
	I_WOOL,					//324
	I_CASHMERE,				//325
	I_POISON,				//326
	I_GARMENT,				//327
	I_PEARL,				//328
	I_OIL,					//329
	I_CHAIN,				//330
	I_GEM,					//331
	I_JEWELRY,				//332
	I_MIRROR,				//333
	I_ORNAMENT,				//334
	I_NECKLACE,				//335
	I_FURNITURE,				//336
	I_STRONGBOX,				//337
	I_IDOL,					//338
	I_STATUE,				//339
	I_FIGURINE,				//340
	I_TALISMAN,				//341
	I_FUR,					//342
	I_PELT,					//343
	I_FURCOAT,				//344
	I_PELTCOAT,				//345
	I_PERFUME,				//346
	I_HEALINGDRAFT,				//347
	I_MEDICINE,				//348
	I_HEALINGPOTION,			//350
	I_RING,					//351
	//tools
	I_SPINNINGWHEEL,			//352
	I_BARREL,				//353
	I_WAGON,				//354
	I_OXCART,				//355
	I_CARRIAGE,				//356
	I_LIZARDWAGON,				//357
	I_LIZARDCART,				//358
	I_LIZARDCARRIAGE,			//359
	I_PRESS,				//360
	I_LOOM,					//361
	I_HARP,					//362
	I_GLIDER,				//363
	I_BAG,					//366
	I_CUTLERY,				//367
	I_SAW,					//368
	I_CHISEL,				//369
	//weapons
	I_NET,					//370
	I_LASSO,				//371
	I_JAVELIN,				//372
	I_ENCHANTEDJAVELIN,			//373
	I_PICK,					//374
	I_ENCHANTEDPICK,			//375
	I_KNIFE,				//376
	I_ENCHANTEDKNIFE,			//377
	I_AXE,					//378
	I_ENCHANTEDAXE,				//379
	I_HAMMER,				//380
	I_ENCHANTEDHAMMER,			//381

	I_LIGHTCROSSBOW,			//382
	I_ENHANTEDLIGHTCROSSBOW,		//383
	I_CROSSBOW,				//384
	I_HEAVYCROSSBOW,			//385

	I_SHORTBOW,				//386
	I_ENCHANTEDSHORTBOW,			//387
	I_BOW,					//388
	I_LONGBOW,				//389
	I_ELVENBOW,				//390

	I_SPEAR,				//391
	I_ENRUNEDSPEAR,				//392
	I_ENCHANTEDSPEAR,			//393
	I_BATTLESPEAR,				//394
	I_WARSPEAR,				//395
	I_FIRESPEAR,				//396
	I_ICESPEAR,				//397

	I_PIKE,					//398
	I_ENCHANTEDPIKE,			//399
	I_HALBERD,				//400
	I_BARDICHE,				//401

	I_LANCE,				//402
	I_ENCHANTEDLANCE,			//403
	I_BATTLELANCE,				//404
	I_WARLANCE,				//405
	I_DUMMYLANCE1,				//406
	I_DUMMYLANCE2,				//407
	I_DUMMYLANCE3,				//408
	I_DUMMYLANCE4,				//409
	I_DUMMYLANCE5,				//410

	I_QUARTERSTAFF,				//411
	I_ENCHANTEDQUARTERSTAFF,		//412
	I_BATTLESTAFF,				//413
	I_WARSTAFF,				//414
	I_MAGESTAFF,				//415
	I_DUMMYSTAFF1,				//416
	I_DUMMYSTAFF2,				//417
	I_DUMMYSTAFF3,				//418
	I_DUMMYSTAFF4,				//419
	I_DUMMYSTAFF5,				//420

	I_CLUB,					//421
	I_ENCHANTEDCLUB,			//422
	I_MACE,					//423
	I_ENCHANTEDMACE,			//424
	I_BATTLEMACE,				//425
	I_WARMACE,				//426

	I_MORNINGSTAR,				//427
	I_ENCHANTEDMORNINGSTAR,			//428
	I_TRISTAR,				//429
	I_EVENINGSTAR,				//430

	I_BATTLEHAMMER,				//431
	I_ENCHANTEDBATTLEHAMMER,		//432
	I_SKULLCRUSHER,				//433
	I_WARHAMMER,				//434

	I_BATTLEAXE,				//435
	I_ENRUNEDAXE,				//436
	I_ENCHANTEDBATTLEAXE,			//437
	I_CLEAVER,				//438
	I_WARAXE,				//439
	I_DWARVINBATTLEAXE,			//440
	I_STARAXE,				//441
	I_SWIFTAXE,				//442

	I_DAGGER,				//443
	I_ENCHANTEDDAGGER,			//444
	I_PARRYINGDAGGER,			//445
	I_ENCHANTEDPARRYINGDAGGER,		//446
	I_MITHRILDAGGER,			//447
	I_ADMANTIUMDAGGER,			//448
	I_RAINBOWDAGGER,			//449

	I_SABRE,				//450
	I_ENCHANTEDSABRE,			//451
	I_EPEE,					//452
	I_FOIL,					//453

	I_SWORD,				//454
	I_ENCHANTEDSWORD,			//455
	I_BROADSWORD,				//456
	I_ENCHANTEDBROADSWORD,			//457
	I_LONGSWORD,				//458
	I_ENCHANTEDLONGSWORD,			//459
	I_MITHRILSWORD,				//460
	I_MITHRILBROADSWORD,			//461
	I_MITHRILLONGSWORD,			//462
	I_ADMANTIUMSWORD,			//463
	I_ADMANTIUMBROADSWORD,			//464
	I_ADMANTIUMLONGSWORD,			//465
	I_DARKSWORD,				//466
	I_FLAMINGSWORD,				//467
	I_ICESWORD,				//468
	I_SOULEATER,				//469
	I_RUNESWORD,				//470

	//armour
	I_SHIELD,				//471
	I_WSHIELD,				//472
	I_ISHIELD,				//473
	I_SSHIELD,				//474
	I_MSHIELD,				//475
	I_ASHIELD,				//476

	I_CLHELMET,				//477
	I_LHELMET,				//478
	I_ICHELMET,				//479
	I_IPHELMET,				//480
	I_SHELMET,				//481
	I_MHELMET,				//482
	I_AHELMET,				//483

	I_CLOTHARMOR,				//484
	I_ENCHANTEDCLOTHARMOR,			//485
	I_LEATHERARMOR,				//486
	I_ENCHANTEDLEATHERARMOR,		//487
	I_BARBARIANPLATE,			//488

	I_IRONCHAINARMOR,			//489
	I_ENCHANTEDCHAINARMOR,			//490
	I_IRONSCALEARMOR,			//491
	I_ENCHANTEDSCALEARMOR,			//492
	I_IRONPLATEARMOR,			//493
	I_ENCHANTEDPLATEARMOR,			//494

	I_STEELCHAINARMOR,			//495
	I_STEELSCALEARMOR,			//496
	I_STEELPLATEARMOR,			//497

	I_MITHRILCHAINARMOR,			//498
	I_MITHRILSCALEARMOR,			//499
	I_MITHRILPLATEARMOR,			//500

	I_ADMANTIUMCHAINARMOR,			//501
	I_ADMANTIUMSCALEARMOR,			//502
	I_ADMANTIUMPLATEARMOR,			//503

	I_DRAGONSCALESARMOR,			//504
	I_CLOAKOFINVULNERABILITY,		//505

	//magic items
	I_BOOTS,				//506
	I_AMULETOFI,				//507
	I_RINGOFI,				//508
	I_STAFFOFF,				//509
	I_STAFFOFICE,				//510
	I_STAFFOFMIND,				//511
	I_STAFFOFL,				//512
	I_AMULETOFTS,				//513
	I_AMULETOFP,				//514
	I_SHIELDSTONE,				//515
	I_CORONETOFPROTECTION,			//516
	I_MCARPET,				//517
	I_PORTAL,				//518
	I_RINGOFWARDING,			//519
	//monster drop magic items
	I_CLOAKOFBLOOD,				//520
	I_STAFFOFPOWER,				//521
	I_STAFFOFFLAME,				//522
	I_STAFFOFCOLDNESS,			//523
	I_BLOODSWORD,				//524
	I_GLASSESOFTRUESIGHT,			//525
	I_CROWNOFINVISIBILITY,			//526
	I_AMULETTOFBEARSTRENGTH,		//527
	I_FEATHERCHARM,				//528
	I_INVISIBILITYPASTE,			//529
	I_WATERMASK,				//530
	I_STAFFOFACIDSHOWER,			//531
	I_AMULETTOFROCSIGHT,			//532
	//skill boost items
	I_IRINGOFSEAMANSHIP,			//533
	I_IRINGOFINCREDIBLECOMBATPROWESS,	//534
	I_IRINGOFHORSEMANSHIP,			//535
	I_IRINGOFAIMING,			//536
	I_IRINGOFARCHERY,			//537
	I_AMULETOFHAUTECUISINE,			//538
	I_AMULETOFARCHITECTURE,			//539
	I_AMULETOFDOCKYARDS,			//540
	I_AMULETOFCARPENTRY,			//541
	I_AMULETOFSMITHCRAFT,			//542
	I_HEALINGCHARM,				//543
	I_FUNNYCHARM,				//544
	I_VEGETABLECHARM,			//545
	I_BEASTCHARM,				//546
	I_FISHCHARM,				//547
	I_WILDERNESSCHARM,			//548
	I_HERBALCHARM,				//549
	I_ORECHARM,				//550
	I_WOODENCHARM,				//551
	I_ROCKCHARM,				//552
	I_PETCHARM,				//553
	//monsters
	I_IDRAGON,				//554
	I_IWOLF,				//555
	I_IEAGLE,				//556
	I_ISKELETON,				//557
	I_IUNDEAD,				//558
	I_ILICH,				//559
	I_IIMP,					//560
	I_IDEMON,				//561
	I_IBALROG,				//562
	I_ISTEELDRAGON,				//563
	I_ICOPPERDRAGON,			//564
	I_IBRONZEDRAGON,			//565
	I_ISILVERDRAGON,			//566
	I_IGOLDENDRAGON,			//567
	I_IGREENDRAGON,				//568
	I_IBROWNDRAGON,				//569
	I_IBLUEDRAGON,				//570
	I_IREDDRAGON,				//571
	I_IWHITEDRAGON,				//572
	I_IBLACKDRAGON,				//573

	I_EAGLE,				//574
	I_WOLF,					//575
	I_SKELETON,				//576
	I_UNDEAD,				//577
	I_LICH,					//578
	I_IMP,					//579
	I_DEMON,				//580
	I_BALROG,				//581
	I_STEELDRAGON,				//582
	I_COPPERDRAGON,				//583
	I_BRONZEDRAGON,				//584
	I_SILVERDRAGON,				//585
	I_GOLDENDRAGON,				//586
	I_GREENDRAGON,				//587
	I_BROWNDRAGON,				//588
	I_BLUEDRAGON,				//589
	I_REDDRAGON,				//590
	I_WHITEDRAGON,				//591
	I_BLACKDRAGON,				//592

	I_STEELDRAGON_S,			//593
	I_COPPERDRAGON_S,			//594
	I_BRONZEDRAGON_S,			//595
	I_SILVERDRAGON_S,			//596
	I_GOLDENDRAGON_S,			//597
	I_STEELDRAGON_O,			//598
	I_COPPERDRAGON_O,			//599
	I_BRONZEDRAGON_O,			//600
	I_SILVERDRAGON_O,			//601
	I_GOLDENDRAGON_O,			//602
	I_STEELDRAGON_A,			//603
	I_COPPERDRAGON_A,			//604
	I_BRONZEDRAGON_A,			//605
	I_SILVERDRAGON_A,			//606
	I_GOLDENDRAGON_A,			//607
	I_STEELDRAGON_B,			//608
	I_COPPERDRAGON_B,			//609
	I_BRONZEDRAGON_B,			//610
	I_SILVERDRAGON_B,			//611
	I_GOLDENDRAGON_B,			//612
	I_GREENDRAGON_S,			//613
	I_BROWNDRAGON_S,			//614
	I_BLUEDRAGON_S,				//615
	I_REDDRAGON_S,				//616
	I_WHITEDRAGON_S,			//617
	I_BLACKDRAGON_S,			//618
	I_GREENDRAGON_O,			//619
	I_BROWNDRAGON_O,			//620
	I_BLUEDRAGON_O,				//621
	I_REDDRAGON_O,				//622
	I_WHITEDRAGON_O,			//623
	I_BLACKDRAGON_O,			//624
	I_GREENDRAGON_A,			//625
	I_BROWNDRAGON_A,			//626
	I_BLUEDRAGON_A,				//627
	I_REDDRAGON_A,				//628
	I_WHITEDRAGON_A,			//629
	I_BLACKDRAGON_A,			//630
	I_GREENDRAGON_B,			//631
	I_BROWNDRAGON_B,			//632
	I_BLUEDRAGON_B,				//633
	I_REDDRAGON_B,				//634
	I_WHITEDRAGON_B,			//635
	I_BLACKDRAGON_B,			//636

	I_CROW,					//637
	I_MOUNTAINLION,				//638
	I_GIANTRAT,				//639
	I_SNAKE,				//640
	I_LION,					//641
	I_ICEWOLF,				//642
	I_POISONSPIDER,				//643
	I_FANGEDLIZARD,				//644
	I_CRAWLER,				//645
	I_LIVINGTREE,				//646
	I_GRIZZLYBEAR,				//647
	I_ROC,					//648
	I_SWAMPCREATURE,			//649
	I_TIGER,				//650
	I_GIANTSCORPION,			//651
	I_POLARBEAR,				//652
	I_GIANTSQUID,				//653
	I_BUGBEAR,				//654
	I_MAULER,				//655
	I_TUNNELWORM,				//656
	I_BOGTHING,				//657
	I_HYDRA,				//658
	I_SPHINX,				//659
	I_KRAKEN,				//660
	I_ILLYRTHID,				//661
	I_THIEF,				//662
	I_HIGHWAYMAN,				//663
	I_GOBLIN,				//664
	I_PIRATE,				//665
	I_MERFOLK,				//666
	I_MUTANT,				//667
	I_CENTAUR,				//668
	I_KOBOLD,				//669
	I_WILDMAN,				//670
	I_SANDLING,				//671
	I_DROWWARRIOR,				//672
	I_EVILWARRIOR,				//673
	I_OGRE,					//674
	I_YETI,					//675
	I_TROLL,				//676
	I_ETTIN,				//677
	I_STORMGIANT,				//678
	I_CLOUDGIANT,				//679
	I_EVILSORCERER,				//680
	I_EVILMAGICIAN,				//681
	I_DARKPRIEST,				//682
	I_ZOMBIE,				//683
	I_RAT,					//684
	I_ANIMATEDTREE,				//685
	I_WILLOWWISP,				//686
	I_CARNIVOROUSPLANT,			//687
	I_KILLERLION,				//688
	I_LONELYCROW,				//689
	I_POISONSNAKE,				//690
	I_WILDBOAR,				//691
	I_LONELYWOLF,				//692
	I_LONELYFANGEDLIZARD,			//693
	I_LONELYPOISONSPIDER,			//694
	I_LONELYCRAWLER,			//695
	I_LONELYEVILWARRIOR,			//696
	I_ROBBER,				//697
	NITEMS
};

//
// Types of men.
//
enum {
	MAN_NONE,				//0
	MAN_LEADER,				//1
	MAN_MAN,				//2
	MAN_TLHUMAN,				//3
	MAN_TRHUMAN,				//4
	MAN_TLVIKING,				//5
	MAN_TRVIKING,				//6
	MAN_TLDERVISH,				//7
	MAN_TRNOMAD,				//8
	MAN_TLBARBARIAN,			//9
	MAN_TRBARBARIAN,			//10
	MAN_TLHIGHLANDER,			//11
	MAN_TRCLANSMAN,				//12
	MAN_TLIMPERIAL,				//13
	MAN_TRIMPERIAL,				//14
	MAN_TLTRIBESMAN,			//15
	MAN_TRTRIBESMAN,			//16
	MAN_TLFFOLK,				//17
	MAN_TRFFOLK,				//18
	MAN_TLCAJUN,				//19
	MAN_TRLIZARDMAN,			//20
	MAN_TLLOWLANDER,			//21
	MAN_TRHALFING,				//22
	MAN_TLELF,				//23
	MAN_TRHALFELF,				//24
	MAN_TLDARKMAN,				//25
	MAN_TRDARKMAN,				//26
	MAN_TLGNOME,				//27
	MAN_TRGNOME,				//28
	MAN_TLDWARF,				//29
	MAN_TRDWARF,				//30
	MAN_TLHOBGOBLIN,			//31
	MAN_TRGOBLIN,				//32
	MAN_TLBUCCANEER,			//33
	MAN_TRBUCCANEER,			//34
	MAN_TLSANDLING,				//35
	MAN_TRSANDLING,				//36
	MAN_TLTROLL,				//37
	MAN_TRGNOLL,				//38
	MAN_TLURUK,				//39
	MAN_TRORC,				//40
	MAN_TLBLACKKEEP,			//41
	MAN_TRBLACKKEEP,			//42
	MAN_TLHEADHUNTER,			//43
	MAN_TRHEADHUNTER,			//44
	MAN_TLOGRE,				//45
	MAN_TROGRE,				//46
	MAN_TLSERPENTPEOPLE,			//47
	MAN_TRSERPENTPEOPLE,			//48
	MAN_TLREPUBLICAN,			//49
	MAN_TRREPUBLICAN,			//50
	MAN_TLAMAZON,				//51
	MAN_TRAMAZON,				//52
	MAN_TLMINOTAUR,				//53
	MAN_TRMINOTAUR,				//54
	MAN_TLDROW,				//55
	MAN_TRDROW,				//56
	MAN_TLDUERGAR,				//57
	MAN_TRDUERGAR,				//58
	MAN_SLAVE,				//59
	MAN_MERC,				//60
	MAN_LHIGHMAN,				//61
	MAN_HIGHMAN,				//62
	MAN_LDARKMAN,				//63
	MAN_DARKMAN,				//64
	MAN_LHIGHLANDER,			//65
	MAN_HIGHLANDER,				//66
	MAN_LBARBARIAN,				//67
	MAN_BARBARIAN,				//68
	MAN_LPLAINSMAN,				//69
	MAN_PLAINSMAN,				//70
	MAN_LHELOT,				//71
	MAN_HELOT,				//72
	MAN_LBEARTRIBE,				//73
	MAN_BEARTRIBE,				//74
	MAN_LNORTHMAN,				//75
	MAN_NORTHMAN,				//76
	MAN_LGYPSY,				//77
	MAN_GYPSY,				//78
	MAN_LWAGONFOLK,				//79
	MAN_WAGONFOLK,				//80
	MAN_LTRIBESMAN,				//81
	MAN_TRIBESMAN,				//82
	MAN_LHEADHUNTER,			//83
	MAN_HEADHUNTER,				//84
	MAN_LWOODSMAN,				//85
	MAN_WOODSMAN,				//86
	MAN_LAMAZON,				//87
	MAN_AMAZON,				//88
	MAN_LHILLMAN,				//89
	MAN_HILLMAN,				//90
	MAN_LHALFORC,				//91
	MAN_HALFORC,				//92
	MAN_LCAVEDWELLER,			//93
	MAN_CAVEDWELLER,			//94
	MAN_LTROGLODYTE,			//95
	MAN_TROGLODYTE,				//96
	MAN_LDEEPFFOLK,				//97
	MAN_DEEPFFOLK,				//98
	MAN_LNIGHTSTALKER,			//99
	MAN_NIGHTSTALKER,			//100
	MAN_LCOMMONMAN,				//101
	MAN_COMMONMAN,				//102
	MAN_LGNOLL,				//103
	MAN_GNOLL,				//104
	MAN_LHILLDWARF,				//105
	MAN_HILLDWARF,				//106
	MAN_LMOUNTAINDWARF,			//107
	MAN_MOUNTAINDWARF,			//108
	MAN_LICEDWARF,				//109
	MAN_ICEDWARF,				//110
	MAN_LDESERTDWARF,			//111
	MAN_DESERTDWARF,			//112
	MAN_LUNDERDWARF,			//113
	MAN_UNDERDWARF,				//114
	MAN_LDARKDWARF,				//115
	MAN_DARKDWARF,				//116
	MAN_LDEEPDWARF,				//117
	MAN_DEEPDWARF,				//118
	MAN_LGULLYDWARF,			//119
	MAN_GULLYDWARF,				//120
	MAN_LWOODELF,				//121
	MAN_WOODELF,				//122
	MAN_LSEAELF,				//123
	MAN_SEAELF,				//124
	MAN_LHIGHELF,				//125
	MAN_HIGHELF,				//126
	MAN_LTRIBALELF,				//127
	MAN_TRIBALELF,				//128
	MAN_LNIGHTELF,				//129
	MAN_NIGHTELF,				//130
	MAN_LDRAGONLORD,			//131
	MAN_DRAGONLORD,				//132
	MAN_LDARKELF,				//133
	MAN_DARKELF,				//134
	MAN_LDEATHWALKER,			//135
	MAN_DEATHWALKER,			//136
	MAN_LORC,				//137
	MAN_ORC,				//138
	MAN_LURUK,				//139
	MAN_URUK,				//140
	MAN_LGOBLINMAN,				//141
	MAN_GOBLINMAN,				//142
	MAN_LOGREMAN,				//143
	MAN_OGREMAN,				//144
	MAN_LHOBBIT,				//145
	MAN_HOBBIT,				//146
	MAN_LGNOME,				//147
	MAN_GNOME,				//148
	MAN_LMINOTAUR,				//149
	MAN_MINOTAUR,				//150
	MAN_LLIZARDMAN,				//151
	MAN_LIZARDMAN,				//152
	MAN_LFAIRY,				//153
	MAN_FAIRY,				//154
	MAN_LTITAN,				//155
	MAN_TITAN,				//156
	MAN_HHIGHMAN,				//157
	MAN_HDARKMAN,				//158
	MAN_HHIGHLANDER,			//159
	MAN_HBARBARIAN,				//160
	MAN_HPLAINSMAN,				//161
	MAN_HHELOT,				//162
	MAN_HBEARTRIBE,				//163
	MAN_HNORTHMAN,				//164
	MAN_HGYPSY,				//165
	MAN_HWAGONFOLK,				//166
	MAN_HTRIBESMAN,				//167
	MAN_HHEADHUNTER,			//168
	MAN_HWOODSMAN,				//169
	MAN_HAMAZON,				//170
	MAN_HHILLMAN,				//171
	MAN_HHALFORC,				//172
	MAN_HCAVEDWELLER,			//173
	MAN_HTROGLODYTE,			//174
	MAN_HDEEPFFOLK,				//175
	MAN_HNIGHTSTALKER,			//176
	MAN_HCOMMONMAN,				//177
	MAN_HGNOLL,				//178
	MAN_HHILLDWARF,				//179
	MAN_HMOUNTAINDWARF,			//180
	MAN_HUNDERDWARF,			//181
	MAN_HDARKDWARF,				//182
	MAN_HDEEPDWARF,				//183
	MAN_HGULLYDWARF,			//184
	MAN_HWOODELF,				//185
	MAN_HSEAELF,				//186
	MAN_HHIGHELF,				//187
	MAN_HTRIBALELF,				//188
	MAN_HNIGHTELF,				//189
	MAN_HDRAGONLORD,			//190
	MAN_HDARKELF,				//191
	MAN_HDEATHWALKER,			//192
	MAN_HORC,				//193
	MAN_HURUK,				//194
	MAN_HGOBLINMAN,				//195
	MAN_HOGREMAN,				//196
	MAN_HHOBBIT,				//197
	MAN_HGNOME,				//198
	MAN_HMINOTAUR,				//199
	MAN_HLIZARDMAN,				//200
	MAN_LHORSEMAN,				//201
	MAN_HORSEMAN,				//202
	MAN_HHORSEMAN,				//203
	MAN_LEASTERLING,			//204
	MAN_EASTERLING,				//205
	MAN_HEASTERLING,			//206
	NUMMAN
};

//
// Types of monsters
//
enum {
  MONSTER_NONE,					//0
  MONSTER_WARG,					//1
  MONSTER_WHOR,					//2
  MONSTER_WLIZ,					//3
  MONSTER_HARY,					//4
  MONSTER_GCEN,					//5
  MONSTER_CHIM,					//6
  MONSTER_WMAM,					//7
  MONSTER_FLIZ,					//8
  MONSTER_HUND,					//9
  MONSTER_CHAR,					//10
  MONSTER_BLIZ,					//11
  MONSTER_UNIC,					//12
  MONSTER_DRAK,					//13
  MONSTER_GRIF,					//14
  MONSTER_WELE,					//15
  MONSTER_FDRA,					//16
  MONSTER_ILLUSION,				//17
  MONSTER_EAGLES,				//18
  MONSTER_STEELDRAGON,				//19
  MONSTER_COPPERDRAGON,				//20
  MONSTER_BRONZEDRAGON,				//21
  MONSTER_SILVERDRAGON,				//22
  MONSTER_GOLDENDRAGON,				//23
  MONSTER_ZOMBIE,				//24
  MONSTER_RAT,					//25
  MONSTER_THIEF,				//26
  MONSTER_ANIMATEDTREE,				//27
  MONSTER_WILLOWWISP,				//28
  MONSTER_CARNIVOROUSPLANT,			//29
  MONSTER_KILLERLION,				//30
  MONSTER_CROW,					//31
  MONSTER_SNAKE,				//32
  MONSTER_WILDBOAR,				//33
  MONSTER_WOLF,					//34
  MONSTER_FANGEDLIZARD,				//35
  MONSTER_POISONSPIDER,				//36
  MONSTER_CRAWLER,				//37
  MONSTER_EVILWARRIOR,				//38
  MONSTER_HIGHWAYMAN,				//39
  MONSTER_ROBBER,				//40
  MONSTER_WOLVES,				//41
  MONSTER_CROWS,				//42
  MONSTER_MOUNTAINLIONS,			//43
  MONSTER_GIANTRATS,				//44
  MONSTER_SNAKES,				//45
  MONSTER_LIONS,				//46
  MONSTER_ICEWOLVES,				//47
  MONSTER_POISONSPIDERS,			//48
  MONSTER_FANGEDLIZARDS,			//49
  MONSTER_CRAWLERS,				//50
  MONSTER_LIVINGTREES,				//51
  MONSTER_GRIZZLYBEARS,				//52
  MONSTER_ROCS,					//53
  MONSTER_SWAMPCREATURES,			//54
  MONSTER_TIGERS,				//55
  MONSTER_GIANTSCORPIONS,			//56
  MONSTER_POLARBEARS,				//57
  MONSTER_GIANTSQUID,				//58
  MONSTER_BUGBEARS,				//59
  MONSTER_MAULER,				//60
  MONSTER_TUNNELWORM,				//61
  MONSTER_GREENDRAGON,				//62
  MONSTER_BROWNDRAGON,				//63
  MONSTER_BLUEDRAGON,				//64
  MONSTER_REDDRAGON,				//65
  MONSTER_WHITEDRAGON,				//66
  MONSTER_BLACKDRAGON,				//67
  MONSTER_BOGTHING,				//68
  MONSTER_HYDRA,				//69
  MONSTER_SPHINX,				//70
  MONSTER_KRAKEN,				//71
  MONSTER_ILLYRTHIL,				//72
  MONSTER_GOBLINS,				//73
  MONSTER_SKELETONS,				//74
  MONSTER_IMPS,					//75
  MONSTER_PIRATES,				//76
  MONSTER_MERFOLK,				//77
  MONSTER_MUTANTS,				//78
  MONSTER_CENTAURS,				//79
  MONSTER_KOBOLDS,				//80
  MONSTER_WILDMEN,				//81
  MONSTER_SANDLINGS,				//82
  MONSTER_DROWWARRIORS,				//83
  MONSTER_EVILWARRIORS,				//84
  MONSTER_OGRES,				//85
  MONSTER_YETIS,				//86
  MONSTER_TROLLS,				//87
  MONSTER_ETTINS,				//88
  MONSTER_UNDEAD,				//89
  MONSTER_DEMONS,				//90
  MONSTER_BALROG,				//91
  MONSTER_LICH,					//92
  MONSTER_STORMGIANT,				//93
  MONSTER_CLOUDGIANT,				//94
  MONSTER_EVILSORCERERS,			//95
  MONSTER_EVILMAGICIANS,			//96
  MONSTER_DARKPRIEST,				//97
  MONSTER_STEELDRAGON_S,			//98
  MONSTER_COPPERDRAGON_S,			//99
  MONSTER_BRONZEDRAGON_S,			//100
  MONSTER_SILVERDRAGON_S,			//101
  MONSTER_GOLDENDRAGON_S,			//102
  MONSTER_STEELDRAGON_O,			//103
  MONSTER_COPPERDRAGON_O,			//104
  MONSTER_BRONZEDRAGON_O,			//105
  MONSTER_SILVERDRAGON_O,			//106
  MONSTER_GOLDENDRAGON_O,			//107
  MONSTER_STEELDRAGON_A,			//108
  MONSTER_COPPERDRAGON_A,			//109
  MONSTER_BRONZEDRAGON_A,			//110
  MONSTER_SILVERDRAGON_A,			//111
  MONSTER_GOLDENDRAGON_A,			//112
  MONSTER_STEELDRAGON_B,			//113
  MONSTER_COPPERDRAGON_B,			//114
  MONSTER_BRONZEDRAGON_B,			//115
  MONSTER_SILVERDRAGON_B,			//116
  MONSTER_GOLDENDRAGON_B,			//117
  MONSTER_GREENDRAGON_S,			//118
  MONSTER_BROWNDRAGON_S,			//119
  MONSTER_BLUEDRAGON_S,				//120
  MONSTER_REDDRAGON_S,				//121
  MONSTER_WHITEDRAGON_S,			//122
  MONSTER_BLACKDRAGON_S,			//123
  MONSTER_GREENDRAGON_O,			//124
  MONSTER_BROWNDRAGON_O,			//125
  MONSTER_BLUEDRAGON_O,				//126
  MONSTER_REDDRAGON_O,				//127
  MONSTER_WHITEDRAGON_O,			//128
  MONSTER_BLACKDRAGON_O,			//129
  MONSTER_GREENDRAGON_A,			//130
  MONSTER_BROWNDRAGON_A,			//131
  MONSTER_BLUEDRAGON_A,				//132
  MONSTER_REDDRAGON_A,				//133
  MONSTER_WHITEDRAGON_A,			//134
  MONSTER_BLACKDRAGON_A,			//135
  MONSTER_GREENDRAGON_B,			//136
  MONSTER_BROWNDRAGON_B,			//137
  MONSTER_BLUEDRAGON_B,				//138
  MONSTER_REDDRAGON_B,				//139
  MONSTER_WHITEDRAGON_B,			//140
  MONSTER_BLACKDRAGON_B,			//141
  MONSTER_DDRA,					//142
  MONSTER_SDRA,					//143
  MONSTER_CDRA,					//144
  MONSTER_RDRA,					//145
  MONSTER_WALKINGFORTRESS,			//146
  MONSTER_BEHEMOTH,				//147
  NUMMONSTERS
};

//
// Types of weapons
//
enum {
	WEAPON_NONE,				//
	WEAPON_RAINBOWDAGGER,			//
	WEAPON_DARKSWORD,			//
	WEAPON_STARAXE,				//
	WEAPON_RUNESWORD,			//
	WEAPON_BLOODSWORD,			//
	WEAPON_SOULEATER,
	WEAPON_ICESWORD,
	WEAPON_FLAMINGSWORD,			//
	WEAPON_LONGBOW,				//
	WEAPON_HEAVYCROSSBOW,			//
	WEAPON_CROSSBOW,			//
	WEAPON_BOW,				//
	WEAPON_ENCHANTEDSHORTBOW,		//
	WEAPON_ENCHANTEDLIGHTCROSSBOW,		//
	WEAPON_SHORTBOW,			//
	WEAPON_LIGHTCROSSBOW,			//
	WEAPON_ENCHANTEDJAVELIN,		//
	WEAPON_JAVELIN,				//
	WEAPON_MAGESTAFF,			//
	WEAPON_SWIFTAXE,			//
	WEAPON_ICESPEAR,			//
	WEAPON_FIRESPEAR,			//
	WEAPON_DWARVINBATTLEAXE,		//
	WEAPON_ADLONGSWORD,			//
	WEAPON_FOIL,				//
	WEAPON_WARHAMMER,			//
	WEAPON_WARMACE,				//
	WEAPON_ADBROADSWORD,			//
	WEAPON_BARDICHE,			//
	WEAPON_WARAXE,				//
	WEAPON_ADSWORD,				//
	WEAPON_WARLANCE,			//
	WEAPON_WARSPEAR,			//
	WEAPON_WARSTAFF,			//
	WEAPON_EVENINGSTAR,			//
	WEAPON_MILONGSWORD,			//
	WEAPON_EPEE,				//
	WEAPON_SKULLCRUSHER,			//
	WEAPON_MIBROADSWORD,			//
	WEAPON_BATTLEMACE,			//
	WEAPON_ENCHANTEDLONGSWORD,		//
	WEAPON_CLEAVER,				//
	WEAPON_HALBERD,				//
	WEAPON_ADDAGGER,			//
	WEAPON_ENCHANTEDSABRE,			//
	WEAPON_MISWORD,				//
	WEAPON_ENCHANTEDBATTLEHAMMER,		//
	WEAPON_ENCHANTEDBROADSWORD,		//
	WEAPON_ENCHANTEDMACE,			//
	WEAPON_BATTLELANCE,			//
	WEAPON_BATTLESPEAR,			//
	WEAPON_TRISTAR,				//
	WEAPON_ENCHANTEDBATTLEAXE,		//
	WEAPON_ENCHANTEDPIKE,			//
	WEAPON_BATTLESTAFF,			//
	WEAPON_ENCHANTEDSWORD,			//
	WEAPON_ENCHANTEDLANCE,			//
	WEAPON_ENCHANTEDSPEAR,			//
	WEAPON_ENCHANTEDMORNINGSTAR,		//
	WEAPON_ENCHANTEDQUARTERSTAFF,		//
	WEAPON_MIDAGGER,			//
	WEAPON_ENCHANTEDDAGGER,			//
	WEAPON_ENCHANTEDKNIFE,			//
	WEAPON_LONGSWORD,			//
	WEAPON_ENCHANTEDCLUB,			//
	WEAPON_ENCHANTEDHAMMER,			//
	WEAPON_ENCHANTEDAXE,			//
	WEAPON_ENCHANTEDPICK,			//
	WEAPON_ENCHANTEDPARRYINGDAGGER,		//
	WEAPON_SABRE,				//
	WEAPON_BATTLEHAMMER,			//
	WEAPON_BROADSWORD,			//
	WEAPON_MACE,				//
	WEAPON_ENRUNEDAXE,			//
	WEAPON_BATTLEAXE,			//
	WEAPON_PIKE,				//
	WEAPON_SWORD,				//
	WEAPON_LANCE,				//
	WEAPON_ENRUNEDSPEAR,			//
	WEAPON_SPEAR,				//
	WEAPON_MORNINGSTAR,			//
	WEAPON_QUARTERSTAFF,			//
	WEAPON_HAMMER,				//
	WEAPON_AXE,				//
	WEAPON_PICK,				//
	WEAPON_DAGGER,				//
	WEAPON_CLUB,				//
	WEAPON_PDAGGER,				//
	WEAPON_KNIFE,				//
	WEAPON_LASSO,				//
	WEAPON_NET,				//
	NUMWEAPONS
};

//
// Types of armor
//
enum {
	ARMOR_NONE,				//
	ARMOR_CLOAKOFI,				//
	ARMOR_DRAGONSCALESARMOR,		//
	ARMOR_CLOAKOFBLOOD,			//
	ARMOR_ADMANTIUMPLATEARMOR,		//
	ARMOR_ADMANTIUMSCALEARMOR,		//
	ARMOR_ADMANTIUMCHAINARMOR,		//
	ARMOR_MITHRILPLATEARMOR,		//
	ARMOR_MITHRILSCALEARMOR,		//
	ARMOR_MITHRILCHAINARMOR,		//
	ARMOR_ENCHANTEDPLATEARMOR,		//
	ARMOR_ENCHANTEDSCALEARMOR,		//
	ARMOR_ENCHANTEDCHAINARMOR,		//
	ARMOR_STEELPLATEARMOR,			//
	ARMOR_STEELSCALEARMOR,			//
	ARMOR_STEELCHAINARMOR,			//
	ARMOR_IRONPLATEARMOR,			//
	ARMOR_IRONSCALEARMOR,			//
	ARMOR_IRONCHAINARMOR,			//
	ARMOR_BPLATE,				//
	ARMOR_ENCHANTEDLEATHERARMOR,		//
	ARMOR_ENCHANTEDCLOTHARMOR,		//
	ARMOR_LEATHERARMOR,			//
	ARMOR_CLOTHARMOR,			//
	ARMOR_SHIELD,				//
	ARMOR_ASHIELD,				//
	ARMOR_MSHIELD,				//
	ARMOR_SSHIELD,				//
	ARMOR_ISHIELD,				//
	ARMOR_WSHIELD,				//
	NUMARMORS
};

//
// Types of mounts
//
enum {
	MOUNT_NONE,				//
	MOUNT_MAMM,				//
	MOUNT_ELEP,				//
	MOUNT_MOLE,				//
	MOUNT_WING,				//
	MOUNT_MFLI,				//
	MOUNT_BATTLELIZARD,
	MOUNT_CHARGER,
	MOUNT_WARLIZARD,
	MOUNT_WARHORSE,
	MOUNT_MEAG,				//
	MOUNT_MBAT,				//
	MOUNT_HUNTINGDOG,
	MOUNT_WARDOG,
	MOUNT_CAME,				//
	MOUNT_MLIZ,				//
	MOUNT_HORS,				//
	MOUNT_MWOL,				//
	MOUNT_MSPI,				//
	MOUNT_PONY,				//
	NUMMOUNTS
};

//
// Other battle items
//
enum {
	BATTLE_NONE,				//
	BATTLE_RUNESWORD,			//
	BATTLE_STAFFOFL,			//
	BATTLE_STAFFOFM,			//
	BATTLE_STAFFOFI,			//
	BATTLE_STAFFOFF,			//
	BATTLE_SOULEATER,			//
	BATTLE_ICESWORD,			//
	BATTLE_FLAMINGSWORD,			//
	BATTLE_MAGESTAFF,			//
	BATTLE_AOFI,				//
	BATTLE_CORONETOFP,			//
	BATTLE_AMULETOFP,			//
	BATTLE_STAFFOFPOWER,			//
	BATTLE_STAFFOFFLAME,			//
	BATTLE_STAFFOFCOLDNESS,			//
	BATTLE_STAFFOFACIDSHOWER,		//
	BATTLE_SHIELDSTONE,			//
	NUMBATTLEITEMS
};

//
// Types of skills.
//
enum {
	S_MINING,				//0
	S_LUMBERJACK,				//1
	S_QUARRYING,				//2
	S_HUNTING,				//3
	S_FISHING,				//4
	S_HERBLORE,				//5
	S_SMITHING,				//6
	S_TOOLMAKING,				//7
	S_BUILDING,				//8
	S_SHIPBUILDING,				//9
	S_ENTERTAINMENT,			//10
	S_TACTICS,				//11
	S_COMBAT,				//12
	S_RIDING,				//13
	S_CROSSBOW,				//14
	S_ARCHERY,				//15
	S_STEALTH,				//16
	S_OBSERVATION,				//17
	S_HEALING,				//18
	S_SAILING,				//19
	S_FARMING,				//20
	S_RANCHING,				//21
	S_WEAPONCRAFT,				//22
	S_ARMORCRAFT,				//23
	S_GEMCUTTING,				//24
	S_ANIMALTRAINING,			//25
	S_ANIMALTAMING,				//26
	S_MONSTERTAMING,			//27
	S_COOKING,				//28
	S_MANIPULATE,				//29
	S_FORCE,				//30
	S_PATTERN,				//31
	S_SPIRIT,				//32
	S_FIRE,					//33
	S_ICE,					//34
	S_MIND,					//35
	S_EARTHQUAKE,				//36
	S_FORCE_SHIELD,				//37
	S_ENERGY_SHIELD,			//38
	S_WEATHER_SHIELD,			//39
	S_SPIRIT_SHIELD,			//40
	S_MAGICAL_HEALING,			//41
	S_GATE_LORE,				//42
	S_FARSIGHT,				//43
	S_TELEPORTATION,			//44
	S_PORTAL_LORE,				//45
	S_MIND_READING,				//46
	S_WEATHER_LORE,				//47
	S_SUMMON_WIND,				//48
	S_SUMMON_STORM,				//49
	S_SUMMON_TORNADO,			//50
	S_CALL_LIGHTNING,			//51
	S_CLEAR_SKIES,				//52
	S_EARTH_LORE,				//53
	S_WOLF_LORE,				//54
	S_BIRD_LORE,				//55
	S_DRAGON_LORE,				//56
	S_WYRM_LORE,				//57
	S_SUMMON_DRAGON,			//58
	S_SUMMON_WYRM,				//59
	S_NECROMANCY,				//60
	S_SUMMON_SKELETONS,			//61
	S_RAISE_UNDEAD,				//62
	S_SUMMON_LICH,				//63
	S_CREATE_AURA_OF_FEAR,			//64
	S_SUMMON_BLACK_WIND,			//65
	S_ENERGY_BLAST,				//66
	S_BANISH_UNDEAD,			//67
	S_DEMON_LORE,				//68
	S_SUMMON_IMPS,				//69
	S_SUMMON_DEMON,				//70
	S_SUMMON_BALROG,			//71
	S_BANISH_DEMONS,			//72
	S_ILLUSION,				//73
	S_PHANTASMAL_ENTERTAINMENT,		//74
	S_CREATE_PHANTASMAL_BEASTS,		//75
	S_CREATE_PHANTASMAL_UNDEAD,		//76
	S_CREATE_PHANTASMAL_DEMONS,		//77
	S_INVISIBILITY,				//78
	S_TRUE_SEEING,				//79
	S_DISPEL_ILLUSIONS,			//80
	S_ARTIFACT_LORE,			//81
	S_CREATE_RING_OF_INVISIBILITY,		//82
	S_CREATE_CLOAK_OF_INVULNERABILITY,	//83
	S_CREATE_STAFF_OF_FIRE,			//84
	S_CREATE_STAFF_OF_LIGHTNING,		//85
	S_CREATE_AMULET_OF_TRUE_SEEING,		//86
	S_CREATE_AMULET_OF_PROTECTION,		//87
	S_CREATE_RUNESWORD,			//88
	S_CREATE_FLAMING_SWORD,			//89
	S_CREATE_SHIELDSTONE,			//90
	S_CREATE_MAGIC_CARPET,			//91
	S_ENGRAVE_RUNES_OF_WARDING,		//92
	S_CONSTRUCT_GATE,			//93
	S_ENCHANT_WEAPONS,			//94
	S_ENCHANT_ARMOR,			//95
	S_CONSTRUCT_PORTAL,			//96
	S_CREATE_FOOD,				//97
	S_CREATE_ICE_SWORD,
	S_CREATE_SOUL_EATER,
	S_CREATE_STAFF_OF_ICE,
	S_CREATE_STAFF_OF_MIND,
	S_CREATE_CORONET_OF_PROTECTION,
	S_SCOUTING,
	S_ENCHANT_RINGS,
	S_ENCHANT_AMULETS,
	S_CREATE_CHARMS,
	NSKILLS
};

//
// Types of special attacks
//
enum {
	SPECIAL_NONE_DUMMY,			//
	SPECIAL_FIREBALL,			//
	SPECIAL_ICECONE,			//
	SPECIAL_MINDSTRIKE,			//
	SPECIAL_HELLFIRE,			//
	SPECIAL_CAUSEFEAR,			//
	SPECIAL_LSTRIKE,			//
	SPECIAL_MINDBLAST,			//
	SPECIAL_EARTHQUAKE,			//
	SPECIAL_TRAMPLING,			//
	SPECIAL_FORCE_SHIELD,			//
	SPECIAL_ENERGY_SHIELD,			//
	SPECIAL_WEATHER_SHIELD,			//
	SPECIAL_SPIRIT_SHIELD,			//
	SPECIAL_DISPEL_ILLUSIONS,		//
	SPECIAL_SUMMON_STORM,			//
	SPECIAL_TORNADO,			//
	SPECIAL_BLACK_WIND,			//
	SPECIAL_ENERGY_BLAST,			//
	SPECIAL_BANISH_UNDEAD,			//
	SPECIAL_BANISH_DEMONS,			//
	SPECIAL_FIREBREATH,			//
	SPECIAL_POISONBREATH,			//
	SPECIAL_ICEBREATH,			//
	SPECIAL_CAMEL_FEAR,			//
	SPECIAL_INVULNERABILITY,		//
	SPECIAL_MAGESTAFF,			//
	SPECIAL_RAINBOW,			//
	SPECIAL_ACIDSHOWER,			//
	NUMSPECIALS
};

//
// Types of objects.
//
enum {
	O_DUMMY,				//0
	O_ROWINGBOAT,				//1
	O_LONGBOAT,				//2
	O_PINK,  				//3
	O_GALLEON,				//4
	O_WARGALLEY,				//5
	O_WARGALLEON,				//6
	O_AIRSHIP,				//7
	O_HERMITSHUT,				//8
	O_TOWER,				//9
	O_GRANDTOWER,				//10
	O_STOCKADE,				//11
	O_GRANDSTOCKADE,			//12
	O_FORT,					//13
	O_GRANDFORT,				//14
	O_CASTLE,				//15
	O_GRANDCASTLE,				//16
	O_CITADEL,				//17
	O_GRANDCITADEL,				//18
	O_FORTRESS,				//19
	O_GRANDFORTRESS,			//20
	O_MAGICALTOWER,				//21
	O_MAGICALCASTLE,			//22
	O_MAGICALFORTRESS,			//23
	O_PALACE,				//24
	O_CPALACE,				//25
	O_CLOUDPALACE,				//26
	O_HTOWER,				//27
	O_HPTOWER,				//28
	O_NGUILD,				//29
	O_AGUILD,				//30
	O_GDCLIFFS,				//31
	O_EDCLIFFS,				//32
	O_SHAFT,				//33
	O_GREENLAIR,				//34
	O_BROWNLAIR,				//35
	O_BLUELAIR,				//36
	O_REDLAIR,				//37
	O_WHITELAIR,				//38
	O_BLACKLAIR,				//39
	O_RUIN,					//40
	O_CAVE,					//41
	O_DEMONPIT,				//42
	O_CRYPT,				//43
	O_ISLE,					//44
	O_DERELICT,				//45
	O_PEATBOG,				//46
	O_WHIRL,				//47
	O_MAGETOWER,				//48
	O_DARKTOWER,				//49
	O_GIANTCASTLE,				//50
	O_ILAIR,				//51
	O_ICECAVE,				//52
	O_THICKET,				//53
	O_PYRAMID,				//54
	O_BKEEP,				//55
	O_ATEMPLE,				//56
	O_TEMPLE,				//57
	O_HUT,					//58
	O_HOUSE,				//59
	O_AQUEDUCT,				//60
	O_INN,					//61
	O_FAIR,					//62
	O_FARM,					//63
	O_MILL,					//64
	O_MUSHROOMFARM,				//65
	O_IRRIGATION,				//66
	O_VINEYARD,				//67
	O_WINEPRESS,				//68
	O_COTTONPLANTATION,			//69
	O_COTTONCOLLECTORS,			//70
	O_TRUFFLESPLANTATION,			//71
	O_BOARPEN,				//72
	O_TOBACCOPLANTATION,			//73
	O_HORTICULTURE,				//74
	O_SHEEPFARM,				//75
	O_SHEEPDIP,				//76
	O_WOOLINGERFARM,			//77
	O_WOOLINGERDIP,				//78
	O_RANCH,				//79
	O_SLAUGHTERHOUSE,			//80
	O_LIZARDRANCH,				//81
	O_LIZARDSLAUGHTERHOUSE,			//82
	O_SHEPHERDHUT,				//83
	O_MENAGERIE,				//84
	O_FISHINGFLEET,				//85
	O_JETTY,				//86
	O_ARTIFICIALREEF,			//87
	O_DIVINGFLOATS,				//88
	O_WHALINGFLEET,				//89
	O_MINE,					//90
	O_FURNACE,				//91
	O_GEMMINE,				//92
	O_GEMAPPRAISER,				//93
	O_MITHRILMINE,				//94
	O_PROSPECTORSHUT,			//95
	O_ADMANTIUMMINE,			//96
	O_GOLDMINE,				//97
	O_TREENURSERY,				//98
	O_TIMBERYARD,				//99
	O_TREETENDERSHUT,			//100
	O_SAWINGMILL,				//101
	O_YEWGROVE,				//102
	O_QUARRY,				//103
	O_STONECUTTERSHUT,			//104
	O_ROOTSTONEQUARRY,			//105
	O_STONEMASONSHUT,			//106
	O_CORESTONEQUARRY,			//107
	O_HUNTINGHUT,				//108
	O_HUNTINGSTAND,				//109
	O_TRAPPINGHUT,				//110
	O_CAGETRAP,				//111
	O_WALKWAY,				//112
	O_GASTANK,				//113
	O_TRAPPINGLODGE,			//114
	O_HERBGARDEN,				//115
	O_HERBALISTSTORE,			//116
	O_FUNGUSGARDEN,				//117
	O_DRYINGSHED,				//118
	O_DRUIDCIRCLE,				//119
	O_PONYSTABLE,				//120
	O_WOLFPEN,				//121
	O_SPIDERSTABLE,				//122
	O_STABLE,				//123
	O_CAMELSTABLE,				//124
	O_LIZARDSTABLE,				//125
	O_EYRIE,				//126
	O_BATCAVE,				//127
	O_ELEPHANTSTABLE,			//128
	O_MAMMOTHSTABLE,			//129
	O_MOLEBURROW,				//130
	O_WINGEDHORSESTABLE,			//131
	O_FLYINGLIZARDSTABLE,			//132
	O_WARGPIT,				//133
	O_TOURNAMENTCOURSE,			//134
	O_TRAININGPIT,				//135
	O_HARPYNEST,				//136
	O_BREEDINGPIT,				//137
	O_CHIMERAROOST,				//138
	O_MAMMOTHWARSCHOOL,			//139
	O_VOLCANICPOOL,				//140
	O_KENNEL,				//141
	O_TOURNAMENTPARCOURS,			//142
	O_TRAININGPEN,				//143
	O_VIRGINARY,				//144
	O_DRAKENSTEIN,				//145
	O_GRIFFONSTABLE,			//146
	O_ELEPHANTWARSCHOOL,			//147
	O_FIREDRAKECLIFF,			//148
	O_TAVERN,				//149
	O_JOINER,				//150
	O_SMITHY,				//151
	O_WEAPONFORGE,				//152
	O_ARMORFORGE,				//153
	O_TEAMTRAINER,				//154
	O_APOTHECARY,				//155
	O_PELTMONGER,				//156
	O_SCULPTOR,				//157
	O_JEWELER,				//158
	O_FISHERY,				//159
	O_FARMHOUSE,				//160
	O_RANCHHOUSE,				//161
	O_CHANDLER,				//162
	O_RUNEMASTER,				//163
	O_ROADN,				//164
	O_ROADNW,				//165
	O_ROADNE,				//166
	O_ROADSW,				//167
	O_ROADSE,				//168
	O_ROADS,				//169
	O_RAFT,
	O_TEPUKE,
	O_SLOOP,
	O_CUTTER,
	O_SCHOONER,
	O_SNOW,
	O_JUNK,
	O_DHOW,
	O_BRIG,
	O_TARTAN,
	O_CARAVEL,
	O_CARRACK,
	O_GALLEY,
	O_COG,
	O_FLOATINGFORTRESS,
	O_GHOSTSHIP,
	O_BALLOON,
	O_SIGNPOST,
	O_ELEFANTWARSCHOOL,
	O_BEHEMOTHWARSCHOOL,
	NOBJECTS
};

//
// Types of terrain
//
/* ARegion Types */
enum {
	R_OCEAN,				//0
	R_PLAIN,				//1
	R_FOREST,				//2
	R_MOUNTAIN,				//3
	R_SWAMP,				//4
	R_JUNGLE,				//5
	R_DESERT,				//6
	R_TUNDRA,				//7
	R_CAVERN,				//8
	R_UFOREST,				//9
	R_TUNNELS,				//10
	R_NEXUS,				//11
	R_VOLCANO,				//12
	R_LAKE,					//13
	R_ISLAND_PLAIN,				//14
	R_ISLAND_SWAMP,				//15
	R_ISLAND_MOUNTAIN,			//16
	R_T_OCEAN1,				//17
	R_T_PLAIN1,				//18
	R_T_PLAIN2,				//19
	R_T_PLAIN3,				//20
	R_T_LAKE1,				//21
	R_T_LAKE2,				//22
	R_T_LAKE3,				//23
	R_T_FOREST1,				//24
	R_T_FOREST2,				//25
	R_T_FOREST3,				//26
	R_T_MYSTFOREST1,			//27
	R_T_MOUNTAIN1,				//28
	R_T_MOUNTAIN2,				//29
	R_T_MOUNTAIN3,				//30
	R_T_HILL1,				//31
	R_T_HILL2,				//32
	R_T_HILL3,				//33
	R_T_SWAMP1,				//34
	R_T_SWAMP2,				//35
	R_T_SWAMP3,				//36
	R_T_JUNGLE1,				//37
	R_T_JUNGLE2,				//38
	R_T_JUNGLE3,				//39
	R_T_DESERT1,				//40
	R_T_DESERT2,				//41
	R_T_DESERT3,				//42
	R_T_VOLCANO1,				//43
	R_T_TUNDRA1,				//44
	R_T_TUNDRA2,				//45
	R_T_TUNDRA3,				//46
	R_T_CAVERN1,				//47
	R_T_CAVERN2,				//48
	R_T_CAVERN3,				//49
	R_T_UNDERFOREST1,			//50
	R_T_UNDERFOREST2,			//51
	R_T_UNDERFOREST3,			//52
	R_T_TUNNELS1,				//53
	R_T_TUNNELS2,				//54
	R_T_TUNNELS3,				//55
	R_T_GROTTO1,				//56
	R_T_PLAIN4,				//57
	R_T_PLAIN5,				//58
	R_T_PLAIN6,				//59
	R_T_LAKE4,				//60
	R_T_LAKE5,				//61
	R_T_LAKE6,				//62
	R_T_FOREST4,				//63
	R_T_FOREST5,				//64
	R_T_FOREST6,				//65
	R_T_MYSTFOREST2,			//66
	R_T_MOUNTAIN4,				//67
	R_T_MOUNTAIN5,				//68
	R_T_MOUNTAIN6,				//69
	R_T_HILL4,				//70
	R_T_HILL5,				//71
	R_T_HILL6,				//72
	R_T_SWAMP4,				//73
	R_T_SWAMP5,				//74
	R_T_SWAMP6,				//75
	R_T_JUNGLE4,				//76
	R_T_JUNGLE5,				//77
	R_T_JUNGLE6,				//78
	R_T_DESERT4,				//79
	R_T_DESERT5,				//80
	R_T_DESERT6,				//81
	R_T_VOLCANO2,				//82
	R_T_TUNDRA4,				//83
	R_T_TUNDRA5,				//84
	R_T_TUNDRA6,				//85
	R_T_CAVERN4,				//86
	R_T_CAVERN5,				//87
	R_T_CAVERN6,				//88
	R_T_DEEPFOREST1,			//89
	R_T_DEEPFOREST2,			//90
	R_T_DEEPFOREST3,			//91
	R_T_TUNNELS4,				//92
	R_T_TUNNELS5,				//93
	R_T_TUNNELS6,				//94
	R_T_GROTTO2,				//95
	R_CE_OCEAN,				//96
	R_CE_OCEAN1,				//97
	R_CE_GDPLAIN,				//98
	R_CE_GDPLAIN1,				//99
	R_CE_EVPLAIN,				//100
	R_CE_EVPLAIN1,				//101
	R_CE_GDGRASSLAND,			//102
	R_CE_GDGRASSLAND1,			//103
	R_CE_EVGRASSLAND,			//104
	R_CE_EVGRASSLAND1,			//105
	R_CE_GDLAKE,				//106
	R_CE_NELAKE,				//107
	R_CE_EVLAKE,				//108
	R_CE_GDFOREST,				//109
	R_CE_GDFOREST1,				//110
	R_CE_EVFOREST,				//111
	R_CE_EVFOREST1,				//112
	R_CE_MYSTFOREST,			//113
	R_CE_MYSTFOREST1,			//114
	R_CE_GDMOUNTAIN,			//115
	R_CE_GDMOUNTAIN1,			//116
	R_CE_EVMOUNTAIN,			//117
	R_CE_EVMOUNTAIN1,			//118
	R_CE_GDHILL,				//119
	R_CE_GDHILL1,				//120
	R_CE_EVHILL,				//121
	R_CE_EVHILL1,				//122
	R_CE_GDSWAMP,				//123
	R_CE_GDSWAMP1,				//124
	R_CE_EVSWAMP,				//125
	R_CE_EVSWAMP1,				//126
	R_CE_GDJUNGLE,				//127
	R_CE_GDJUNGLE1,				//128
	R_CE_EVJUNGLE,				//129
	R_CE_EVJUNGLE1,				//130
	R_CE_GDDESERT,				//131
	R_CE_GDDESERT1,				//132
	R_CE_EVDESERT,				//133
	R_CE_EVDESERT1,				//134
	R_CE_WASTELAND,				//135
	R_CE_WASTELAND1,			//136
	R_CE_GDTUNDRA,				//137
	R_CE_GDTUNDRA1,				//138
	R_CE_EVTUNDRA,				//139
	R_CE_EVTUNDRA1,				//140
	R_CE_GDCAVERN,				//141
	R_CE_GDCAVERN1,				//142
	R_CE_EVCAVERN,				//143
	R_CE_EVCAVERN1,				//144
	R_CE_GDUFOREST,				//145
	R_CE_GDUFOREST1,			//146
	R_CE_EVUFOREST,				//147
	R_CE_EVUFOREST1,			//148
	R_CE_TUNNELS,				//149
	R_CE_TUNNELS1,				//150
	R_CE_GDULAKE,				//151
	R_CE_NEULAKE,				//152
	R_CE_EVULAKE,				//153
	R_CE_GDDCAVERN,				//154
	R_CE_GDDCAVERN1,			//155
	R_CE_EVDCAVERN,				//156
	R_CE_EVDCAVERN1,			//157
	R_CE_GDDFOREST,				//158
	R_CE_GDDFOREST1,			//159
	R_CE_EVDFOREST,				//160
	R_CE_EVDFOREST1,			//161
	R_CE_DTUNNELS,				//162
	R_CE_DTUNNELS1,				//163
	R_T_MINES1,				//164
	R_T_MINES2,				//165
	R_T_MINES3,				//166
	R_T_MINES4,				//167
	R_T_MINES5,				//168
	R_T_MINES6,				//169
	R_T_CHAMBER1,				//170
	R_T_CHAMBER2,				//171
	R_T_CHAMBER3,				//172
	R_T_CHAMBER4,				//173
	R_T_CHAMBER5,				//174
	R_T_CHAMBER6,				//175
	R_CE_ICE,				//176
	R_CE_GLACIER,				//177
	R_CE_CRYSTALCAVERN,			//178
	R_CE_BLUECAVERN,			//179
	R_CE_REDCAVERN,				//180
	R_CE_YELLOWCAVERN,			//181
	R_CE_ORANGECAVERN,			//182
	R_CE_GREENCAVERN,			//183
	R_CE_VIOLETCAVERN,			//184
	R_CE_BLACKCAVERN,			//185
	R_CE_WHITECAVERN,			//186
	R_CE_GRANITE,				//187
	R_CE_BASALT,				//188
	R_CE_NPLAIN,				//188
	R_CE_NFOREST,				//189
	R_CE_NMOUNTAIN,				//190
	R_CE_NHILLS,				//191
	R_CE_NGRASSLAND,			//192
	R_COASTAL,
	R_NUM
};

// Types of effects
enum {
	EFFECT_DAZZLE,				//
	EFFECT_FEAR,				//
	EFFECT_STORM,				//
	NUMEFFECTS
};

// Types of ranges
enum {
	RANGE_TELEPORT,				//
	RANGE_PORTAL_LORE,			//
	RANGE_FARSIGHT,				//
	RANGE_WEATHER_LORE,			//
	RANGE_CLEAR_SKIES,			//
	NUMRANGES
};

enum {
  SUMMON_BALROG,				//
  SUMMON_DEMON,					//
  SUMMON_IMP,					//
  SUMMON_LICH,					//
  SUMMON_UNDEAD,				//
  SUMMON_SKELETON,				//
  SUMMON_WOLF,					//
  SUMMON_BIRD,					//
  SUMMON_DRAGON,				//
};

#endif
